### ISSUE TITLE
Timer start counting up when finished

### ISSUE THREAD

**Issue by bokf** [SimpleMobileTools/Simple-Clock#105]
I miss a counter once the timer has finished. I want to know how long the timer is over, similar to starting a stopwatch with a minus at the beginning. See cyanogenmod timer.
![screenshot_2018-10-08-13-07-16](https://user-images.githubusercontent.com/25562831/46606122-0d639700-cafc-11e8-9703-1afa669e75d5.png)

**Comment by tibbi** [comment]
it is already htere

**Comment by bokf** [comment]
Now I understand! Because the timer stopped when the screen went off, my bread nearly burned in the oven and I never came to the end of the timer!
