### ISSUE TITLE
Home button makes a mess

### ISSUE THREAD

**Issue by daisybrain** [SimpleMobileTools/Simple-Clock#112]
I have a bunch of alarms and I have noticed a problem. If I set some alarms and then I use a home button, picked alarms change in an unpredictable way: some of them turns off, some other turns on, once I even overslept because of this. An interesting thing that if I use 'back' button instead of 'home', it works in a correct way.

**Comment by daisybrain** [comment]
Yesterday I noticed that if I open general settings or settings of a particular alarm, it also makes that mess.

**Comment by tibbi** [comment]
retry with 5.0.0 please, many things have been rewritten. Reopen if it is still broken.
