### ISSUE TITLE
Alarms auto-starting & auto-stopping upon scrolling in app

### ISSUE THREAD

**Issue by ghost** [SimpleMobileTools/Simple-Clock#117]
Simple Clock v4.3.0, Android 8.1.0, Samsung Note 9 (SM-N960U1)

Upon enabling alarms and scrolling through the app (it'd be about 8 to enable scrolling on my screen specifically), alarms will automatically enable themselves without any input. This behaviour is consistent and only appears to trigger for certain alarms with otherwise identical settings.

As an example - from 00:00 to 02:00, settings alarms every fifteen minutes, alarm 00:00 will automatically enable itself upon scrolling **immediately** past 00:45. Once that entry is hidden, 00:00 will enable. The same situation has occurred with multiple other alarms and does not appear to be related to speed of scrolling. See link below for an example of this behaviour.

https://i.imgur.com/dpkYv9L.gifv

**Comment by tibbi** [comment]
retry with 5.0.0 please, many things have been changed

**Comment by tibbi** [comment]
Reopen if it is still broken.

**Comment by Nomuit** [comment]
Having retried using the 5.0.0 apk in releases, I still encounter the bug in OP - I also encounter the exact opposite, wherein any alarms roughly ~4 alarm heights offscreen will deactivate during scrolling.

The behaviour of both of these bugs is erratic, and seems to occur to specific alarms more frequently than others; alarms that are forced on by the bug do not appear affected by the deactivation bug, at the very least. Linking two example GIFs:

https://i.imgur.com/L3oquUi.gifv
https://i.imgur.com/qXB5vdB.gifv

I should note that I briefly experienced this new bug on 4.3.0. I had uninstalled Simple Clock and reinstalled, but was met with both bugs. I can do any testing that you may need.

**Comment by shiftee** [comment]
Hi,
I've just started using this app and I am having this issue also.

I'm using v4.3.0 from FDroid on LineageOS 15.1
