### ISSUE TITLE
Create alarm for a specific date/time

### ISSUE THREAD

**Issue by savingprivatebryan** [SimpleMobileTools/Simple-Clock#127]
Related to #58 and #38. It's a common use case (for me at least) to create a one-time alarm that goes off on a specific date and time. For example if I have to get up early for a flight, job interview, etc (basically any non repeating event). Sometimes the event is more than a week ahead and would love to be able to create these kinds of alarms like I can with the stock alarm app.

**Comment by Bill-Stewart** [comment]
+1 - Yes, this would be an outstanding feature!

**Comment by 07416** [comment]
There doesn't appear to be any app on F-Droid which has this feature -- I have to use this proprietary app https://play.google.com/store/apps/details?id=com.funanduseful.earlybirdalarm

**Comment by tibbi** [comment]
will be fixed in 5.4.0

**Comment by Bill-Stewart** [comment]
I have 5.4.0 installed and I don't see how to add a future alarm for a specified date. Maybe I am missing something obvious?

**Comment by tibbi** [comment]
right, you cannot specify a future date. It isnt on the roadmap though, just use a calendar event for such cases.

**Comment by 07416** [comment]
> right, you cannot specify a future date. It isnt on the roadmap though, just use a calendar event for such cases.

(Calendar) notifications don't loop based on my experience and I prefer setting the notification volume at 0% to avoid distractions. Last I tried the longer audio track I had set as the notification sound was also cut off very quickly (15 seconds or less).

In my opinion notifications aren't a replacement for alarms and apparently are almost as easy to miss as a typical SMS sound or similar. Would you rely on a single 0,5 second *ping*  sound effect for your alarm?

**Comment by Bill-Stewart** [comment]
> right, you cannot specify a future date. It isnt on the roadmap though, just use a calendar event for such cases.

In that case then this issue should not be closed because it is not yet implemented. As the above comment notes, a calendar notification really isn't a substitute for an alarm.

**Comment by tibbi** [comment]
I still dont plan adding it, so I dont want to have it open unnecessarily.

**Comment by Bill-Stewart** [comment]
Ah. In that case, your initial comment should have been "feature request rejected" or "will not implement" rather than "will be fixed in 5.4.0", then. This is unfortunate, as this feature would be an excellent enhancement to add to this app! I would encourage you to reconsider this request.
