### ISSUE TITLE
Repeat Alarms For Daily Reminders Not Working

### ISSUE THREAD

**Issue by puppykickr** [SimpleMobileTools/Simple-Clock#141]
I need multiple alarms throughout each day.

They will all work fine, but only once.

After the last alarm of the day, the app closes, the alarm indicator in the status bar goes off, and the alarm will not go off the next day.

After the last alarm of the day, I must enter the app in order for the alarm to be set to go off again the next day.

Poblano VLE5 8.1.0
App version 5.0.2

**Comment by puppykickr** [comment]
Sorry, it appears that this issue is a rehash of #136.

**Comment by frederickjh** [comment]
> Sorry, it appears that this issue is a rehash of #136.
In that case @puppykickr you should close this issue and subscribe / add your voice to #136.
