### ISSUE TITLE
Pre-selecting weekday when setting new alarms

### ISSUE THREAD

**Issue by lianergoist** [SimpleMobileTools/Simple-Clock#146]
It would be cool  if the app automatically suggested a weekday to fire the alarm. Fx. if the user at 13:00 creates a new alarm to fire at 15:00, it should set it (pre-set/suggest) to same day, but if the alarm is set to 06:00, it should be set to next day. 

Maybe a label in the dialog could also say: 'alarm will fire in x days and x hours and x minutes', or something like that.

**Comment by tibbi** [comment]
selecting the next day by default has already been added. The message after enabling an alarm say when will it fire
