### ISSUE TITLE
Alarms: automatically select just next recurrence if no day is set

### ISSUE THREAD

**Issue by davidecalza** [SimpleMobileTools/Simple-Clock#148]
Sometimes we need to set an alarm that does not need any repetition.

The expected behavior is the alarm to automatically trigger at the next recurrence if I set no daily repetition, and then never trigger again if not turned on manually.

The actual behavior consist in the impossibility to set an alarm without selecting at least one day. In this way, I am forced to set a day and, in case I forgot to turn it off, it will trigger again over and over.

**Comment by ltGuillaume** [comment]
Exactly. Choosing the day for repetition is definitely not the default behavior for me: I almost never set a repeating alarm. I'd very much like to bump priority for this! 😁

**Comment by Thorsky24** [comment]
I came here to say the same thing. The app is pretty good, but this feature is probably the biggest improvement that could be made. Hopefully that will be soon implemented!

**Comment by Adda0** [comment]
I don't understand how any alarm/clock application does not have this option yet, but here we are. Unfortunately, this makes Simple Clock unusable for me. I really hope this will be implemented someday soon.

**Comment by tibbi** [comment]
will be fixed in 5.4.0
