### ISSUE TITLE
bug found while launching simple clock

### ISSUE THREAD

**Issue by djavalord** [SimpleMobileTools/Simple-Clock#15]
#### Expected behavior
click on the simple clock launcher, then it should open

#### Actual behavior
click on the simple clock launched but it did not open

#### How to reproduce
download from F-Droid, then click on the shortcut to launch. or click on the run from the F-Droid after installation 

* Browser: simple clock  version 3.1.0
* Operating system: Android 5.1.1 Lollipop. Infinix hot 3 LTE

#### Recording Of The Bug
https://youtu.be/lD13Z0u6KSY
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@javalord/bug-found-while-launching-simple-clock">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by tibbi** [comment]
should be fixed in 3.1.2, we will see
