### ISSUE TITLE
Detail build process in readme.

### ISSUE THREAD

**Issue by dietercastel** [SimpleMobileTools/Simple-Clock#150]
It would be nice to have the build process for this app detailed in the Readme.

I'll make a PR for this soon since I plan to look into helping out a bit here so you can assign me. 

Is it just running `gradle build` after cloning this? Any dependencies to install besides standard android & jdk?

**Comment by tibbi** [comment]
just press Build in Android Studio, there is nothing special whatsoever in the app. You should start android development with some hello world, not this one though. Thanks
