### ISSUE TITLE
Alarm does not update on summer/winter time change

### ISSUE THREAD

**Issue by davidecalza** [SimpleMobileTools/Simple-Clock#151]
On change from summertime to winter time, alarms have not been updated so they would trigger one hour before usual.

E.g. 
1) Alarm set at 07:00 AM
2) Summertime to wintertime change
3) Alarm changes to 06:00 AM

**Comment by J4gQBqqR** [comment]
Oh, well, a feature request known for two years...
Thanks for the pointer.

**Comment by grrrrr** [comment]
@tibbi could the label be changed to **bug**,  this should not be seen as a feature request as the hour change results in alarms ringing at the wrong time.

**Comment by tibbi** [comment]
it doesnt matter what label is there... This app has been abandoned so it wont be fixed anytime soon.

**Comment by tibbi** [comment]
duplicate of #131
