### ISSUE TITLE
centered widget

### ISSUE THREAD

**Issue by M1Aston** [SimpleMobileTools/Simple-Clock#152]
I can't get the widget centered horizontally on my Sony Xperia. After dragging it to position where I want it to be, it automatically moves slightly left or right. It is always off-center.

**Comment by tibbi** [comment]
you mean the widget itself, or the text in it? The widget itself is handled by the home screen, you cannot just place it anywhere. There is kind of a grid in the background that determines the position.

**Comment by M1Aston** [comment]
I mean the text\time.
I had the background set to transparent, so I didn't see that. But after changing that I noticed that there are only two positions possible for the widget: either the left or the right side of the screen.
Simple-Clock replaces the default Sony clock\widget, which can be centred (for what it's worth).

**Comment by tibbi** [comment]
can you maybe send a screenshot of what you mean? Also, what Android OS version do you have?

**Comment by M1Aston** [comment]
To the right. The only alternative is (too far) to the left.
Android 8.0

![Screenshot_2019-11-05_11-23-45](https://user-images.githubusercontent.com/43113612/68199854-1359cf00-ffbf-11e9-88fb-5b49d815b269.png)

**Comment by tibbi** [comment]
It seems to work well. To increase the widget size just long press it, then drag the left side to the left. Thats the way resizing works.

**Comment by M1Aston** [comment]
Ah yes, got it.
What a stupid mistake. Sorry about that.
