### ISSUE TITLE
Alarms cannot sound when screen is locked on Android 10

### ISSUE THREAD

**Issue by lss4** [SimpleMobileTools/Simple-Clock#160]
I'm currently using latest Simple Clock with Havoc 3.0 GSI (Android 10). Alarm only works when the screen is not locked, and in that case, only a heads-up notification appears. The screen which I need to swipe to dismiss the alarm never shows up regardless (although showing only a heads-up notification for alarms when screen is not locked is an intended behavior in Android 10).

I suspect the change in Android 10 which [restricted starting activities from background](https://developer.android.com/guide/components/activities/background-starts) might have caused the alarm to not work properly when the screen is locked.

This change also [broke many other 3rd-party alarm apps](https://support.google.com/pixelphone/thread/13646363?hl=en), so consider this a feature request instead of a bug.

**Comment by lss4** [comment]
Can confirm the issue has indeed been fixed with 5.1. Thanks. :-)

By the way, when will this version be available on F-Droid? It's still 5.0.4 there, although I can obtain the 5.1 from GitHub Releases.

**Comment by tibbi** [comment]
not sure, they are taking care of updating the apps themselves. I will wait a few more days then check if they have some compile errors there or what is happening.

**Comment by eldervamp** [comment]
Well F-Droid is still showing a old version for this app. User mentioned on the F-Droid forums why the version he downloaded from F-Droid was giving issues but not from Google Play Store. 
https://forum.f-droid.org/t/no-notifications-no-sound-from-alarm-apps/9026

**Comment by tibbi** [comment]
f-droid is weird, try asking them why isnt hasnt the app been updated
