### ISSUE TITLE
Bug: removing "Simple Clock" app from the recent tasks, it ruins a scheduled alarm

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [SimpleMobileTools/Simple-Clock#168]
And this occurs on both Pixel 4 and emulator, and not just on some terrible OEM (as shown [here](https://dontkillmyapp.com/)).

See attached video:

[2020-02-20_16-19-22.zip](https://github.com/SimpleMobileTools/Simple-Clock/files/4231191/2020-02-20_16-19-22.zip)

I've waited much longer than what the video shows. If I don't remove from the recent tasks, it works fine.

I think this is a bug on the OS so I reported [here ](https://issuetracker.google.com/issues/149556385).

However, somehow I see it working on some apps, such as [here](https://play.google.com/store/apps/details?id=com.amdroidalarmclock.amdroid). No idea how, so I asked [here](https://stackoverflow.com/q/60079472/878126).

If you know how to fix it, please let me know. I can grant the bounty to you if you wish :)

**Comment by tibbi** [comment]
you should never remove apps from Recents like that, only if the app freezes

**Comment by AndroidDeveloperLB** [comment]
What do you mean "like that" ? 
Users do it all the time.
It's not "force-stop". It's just removing from the recent tasks. 
You are confusing things.
Try it on the Clock app of Google. It will still trigger, as opposed to here.
Look at the attached video for example:

[2020-02-20_22-12-01.zip](https://github.com/SimpleMobileTools/Simple-Clock/files/4232807/2020-02-20_22-12-01.zip)


It works fine on both devices and emulators.

**Comment by AndroidDeveloperLB** [comment]
Removing an app from recent tasks never ruins how an app behaves in terms of scheduling. 
You can do it and still get emails, alarms, messages, calendar events...
It's wrong to say what you wrote.
