### ISSUE TITLE
Remember input method for alarm time

### ISSUE THREAD

**Issue by ltGuillaume** [SimpleMobileTools/Simple-Clock#172]
Personally I hate the time input method, especially on somewhat smaller screens. I always go to "Set time" to type in the hours and minutes, but Simple Clock doesn't remember my preference for this.

It would be great if Simple Clock would remember the last used input method and next time open it automatically.

E: Not sure if this is possible is the time picker is Android's default one, which looks like it...

**Comment by tibbi** [comment]
will be fixed in 5.2.0
