### ISSUE TITLE
Back button CANCELS timer

### ISSUE THREAD

**Issue by ltGuillaume** [SimpleMobileTools/Simple-Clock#173]
When you set a timer, then press the phone's back button to resume your business, the timer is actually _cancelled_, without any notification. I don't think this is the desired behavior.

Simple Clock v5.0.4 on LineageOS 16 (Android 9).

**Comment by tibbi** [comment]
duplicate of #77

**Comment by ltGuillaume** [comment]
Is it? I don't see it, but perhaps it comes down to the same thing under the hood, then?

**Comment by tibbi** [comment]
ye it is the same issue. The current implementation is a really primitive one. It stops once the app stops.

**Comment by ltGuillaume** [comment]
Ah ok, that's a bit tricky then. Need to use a service for that?

**Comment by tibbi** [comment]
maybe, not sure which solution is the best there. I always hated such background service-ish things.

**Comment by ltGuillaume** [comment]
Me too, but afaik it's simpleL an activity can be thrown out any time by Android. Services don't have to be big things, but back when I dabbled with it, I found the broadcasting stuff a bit annoying.
