### ISSUE TITLE
Turn off alarm by pressing the volume keys

### ISSUE THREAD

**Issue by qw123wh** [SimpleMobileTools/Simple-Clock#190]
Turn off the alarm by pressing the volume keys.  This feature is also in aosp clock app

**Comment by odmfl** [comment]
It would be very useful to give functions to the hw keys. Maybe this commit can help you,have a look please @tibbi 

https://github.com/pranavkapoor001/Alarmzy/commit/245f68eb404fe13312eaf72e8f6a2ccfa858878d

**Comment by qw123wh** [comment]
Yes @odmfl I'm trying that app and I love the ability to turn off / snooze ... the alarm with the volume and power buttons.  It's a great app but it's just an alarm clock.  Simple clock on the other hand is a complete clock app, but the alarm clock is very limited without this function.
