### ISSUE TITLE
Alarms Not in Chronological Order

### ISSUE THREAD

**Issue by NoStepSnek** [SimpleMobileTools/Simple-Clock#193]
Alarms are not presenting in Chronological Order in the menu. As someone that uses alarms for everything, this is more of an inconvenience when hunting down a previous alarm to use again.

**Comment by tibbi** [comment]
I dont plan autosorting them, some drag and drop might be added though

**Comment by JamesDean829** [comment]
autosorting would be really useful if there is an option in the settings
