### ISSUE TITLE
alarm not working on Android 10 when app is closed

### ISSUE THREAD

**Issue by guzzisti** [SimpleMobileTools/Simple-Clock#199]
Device: Nokia 2.2
Android Version: Android 10 (Patchlevel 2020.04)
App version: 5.2.1 F-Droid
battery optimization for app: disabled

Alarms only work when the app is opened. Then the clock icon is shown in the status bar.
As soon as the app is closed via the "recent apps" menu, the clock icon disappears and set alarms will not show up anymore.

**Comment by tibbi** [comment]
if you close the app properly with the Back button, does it work?

**Comment by guzzisti** [comment]
Back button keeps the alarm on but does not "close" the app but only sends it to the background.

The same behaviour appears after the phone is restarted, no alarm will show up until the app has been manually opened.

**Comment by tibbi** [comment]
Back button is the way to properly close all apps. You should use swiping from Recents only if apps freeze or so, else they can misbehave.

**Comment by guzzisti** [comment]
So it is intentional that users need to open the app manually after restarting the phone?

**Comment by tibbi** [comment]
no, but Im not responsible for using devices the wrong way

**Comment by Skaalgard** [comment]
What do you mean "using devices the wrong way?" Apps do not close with the back button - they are just minimized. Apps like your clock also do not automatically open when the device is booted; they must be manually started by the user, so your answer here doesn't make any sense.
