### ISSUE TITLE
(suggestion:) after saving alarm show toast when alarm is due

### ISSUE THREAD

**Issue by tusch001** [SimpleMobileTools/Simple-Clock#202]
My old clock app had a feature which I liked:
After saving / changing an alarm it showed a toast when the alarm is due

eg:
it's 2 p.m. and the alarm is due

- today at 6:30 p.m. it said: due in 4 hours 30 minitues
- Sunday at 8:30 a.m.: it said 4 days 16 hours 30 minutes.

This is very useful as I often change an existing alarm instead of creating a new one. It's a check for me because I often don't look at the days that a marked and with the toast I realise that I have marked the wrong days.

Just a suggestion if you ever find time :-)

Thx

**Comment by tibbi** [comment]
it already shows the time remaining to the next alarm at toggling, Ill see how could it be improved further

**Comment by tusch001** [comment]
Guess what - after rebooting the phone I can see the toasts now.  Don't know what went wrong before. Sorry for keeping your time.
