### ISSUE TITLE
Please improve this

### ISSUE THREAD

**Issue by Pranab009** [SimpleMobileTools/Simple-Clock#205]
Hello Devoloper sir, 

Your clock app is tooo good.👍🏼

But please add some more features..plz..plz...

Please add a notification options before 1 hour or 2hour for Dismiss or Snooze alarm. 

It ignore some alarms.

All backup options settings &  alarms time (Activity) Backus

Please maintain chronological order.

Thank you very much for reading this..🙏🏻🙏🏻❤️

**Comment by tibbi** [comment]
report 1 thing per issue please, if they arent reported yet
