### ISSUE TITLE
No ring tone, no dialogue

### ISSUE THREAD

**Issue by Bernie-KN** [SimpleMobileTools/Simple-Clock#208]
Unfortunately there is no ringtone with the alarm clock & timer.
Vibration and little Icon in status bar works independent of notification settings.

Android 10
Xiaomi Redmi Note 8 Pro

Thanx in advance, B.

**Comment by tibbi** [comment]
take a look at your device settings related to audio, battery saving and reminder channels, maybe something is limiting it. Try also creating new alarms for testing, modifying existing alarm sounds might not work as expected.

**Comment by Bernie-KN** [comment]
Hi tibbi & thanx for your quick response!
Batterie saving wasn't the problem, but although i didn't change anything in notification concerning your prog, audio notifications were disabled. With uninstalling & reinstallation all alarm sounds are working fine now.

Btw, after changing the sound for timer, setting will not be be realized until one switches  "vibration" on/off

Greetings, Bernd
