### ISSUE TITLE
Alarm volume is unstable

### ISSUE THREAD

**Issue by giriannamalai** [SimpleMobileTools/Simple-Clock#209]
In the beginning of alarm, the volume is really high. It crosses the volume limit set by the system level. I have disabled increase volume gradually too. High volume first few secs. It even woke up my neighbor.  :smile: 

The alarm volume should not go above the system set level. 
Also, After dismiss the alarm (swiping), It is in the background and showing in recent apps.
If I select the app from the recent apps, The alarms starts again regardless of time.

Android 8.1
Clock version - 5.2.2

**Comment by Github-com-foss** [comment]
Increase volume gradually wont work. (High volume at start) pls fix this issue on next update.
