### ISSUE TITLE
[suggestion] option to sort alarms by time

### ISSUE THREAD

**Issue by DSDV** [SimpleMobileTools/Simple-Clock#215]
hi,
currently all alarms are sorted by date of creation.
an option which sorts them by the time they ring (as it is default for samsung and miui) whould be very nice!

**Comment by summersab** [comment]
+1 to this. It takes me a lot of alarms to wake up, so I have literally dozens of alarms in my list. However, if I don't create all of the alarms sequentially, they may wind up out of order and be a huge mess. For this reason, I've had to use a different (and likely no longer maintained) app.
