### ISSUE TITLE
Alarm ringing twice at the same time

### ISSUE THREAD

**Issue by zelinux0202** [SimpleMobileTools/Simple-Clock#220]
Hey, every time my alarm rings it rings twice with about half a second of delay and it is anoying because it plays the music over itself. I'm running Lineage OS on a exynos S8 with micro g apps.

**Comment by Tetsuo-Hanma** [comment]
> can you reproduce it easily by creating a new alarm? Does it always happen?

I'm running on an LG G7 Thin q and the same issue happens, even if I create a new alarm.

**Comment by ssnor** [comment]
I have the same problem, I'm on a Nexus 6 with Lineage 17.1.

**Comment by SirioSechi** [comment]
I have the same problem, I'm on a Sony Xperia 5. Android 10.
It looks that Simple-Clock get in memory the first alarm that a used for the first alarm that I setted. Now for the others alarms, when I use a mp3 sound it plays at the same time my mp3 and the other sound.

**Comment by BruceMustache** [comment]
The same happens to me on adroid 10 Clock v5.4

**Comment by tibbi** [comment]
retry with 5.8.1
