### ISSUE TITLE
Unable to override locale after 5.3 update

### ISSUE THREAD

**Issue by mraandtux** [SimpleMobileTools/Simple-Clock#223]
In Simple Clock 5.2.2, the "use English language" function is still available:

![Screenshot_2020-09-04-22-42-19-284_com simplemobiletools clock](https://user-images.githubusercontent.com/2002796/92698195-a94c4c00-f37e-11ea-8ba8-97a1036cba7a.jpg)

This is after I tweak the setting in the latest 5.3 release:

![Screenshot_2020-09-04-22-39-36-740_com simplemobiletools clock](https://user-images.githubusercontent.com/2002796/92698152-9df92080-f37e-11ea-84dd-cf9860aa792a.jpg)

**Comment by tibbi** [comment]
does it happen in other apps too? It seems to be a system specific issue, not really related to the language setter itself.

**Comment by tibbi** [comment]
should be fixed in 5.3.2 released soon
