### ISSUE TITLE
No sound with screen off

### ISSUE THREAD

**Issue by oonet** [SimpleMobileTools/Simple-Clock#225]
Simple Clock 5.3.0
Android 10

Notifications wait for screen to be on. There are no alarms while the screen is off.

**Comment by tibbi** [comment]
Hey, check your device battery and notification settings, if there is nothing blocking the reminders, or killing the app in the background.

**Comment by oonet** [comment]
Battery Saver is off. Show notifications is on.

Works fine in background (in home screen or other app) - but not while screen is off.

**Comment by tibbi** [comment]
that doesnt sound like an issue with the app. It must be something with your device settings.

**Comment by oonet** [comment]
Trying several phones, the problem only happens with phone running Android 10.0.

**Comment by tibbi** [comment]
well it is a system issue then, probably something related to some battery or memory restrictions

**Comment by oonet** [comment]
There are no battery or memory restrictions. It appears to be a peculiarity with Android 10.0.

Trying other clocks at random with Android 10.0, some (that work perfectly in older Andoid phons) have the same problem. Others work as expected.
