### ISSUE TITLE
My experience with App version 5.4.0

### ISSUE THREAD

**Issue by Asiaboy89** [SimpleMobileTools/Simple-Clock#237]
Device: Honor 10 (Build number: 10.0.0.180(C432E5R1P4patch01), EMUI Version: 10.0.0, Android Version: 10)
Simple-Clock App Version: 5.4.0

### Feature Request:

1. **Clock**: There should be much more countries to choose from for the time zones, e.g. missing Tahiti (French Polynesia) or Miami (USA), etc. Here you could use the selection of the standard clock App from e.g. Huawei/Honor (they have much more countries or cities)
2. **Alarm**: Permanently show PER alarm, how much time will remain until the next setted alarm will ring (currently only shown in a 3-second popup at the bottom when the alarm is activated) -> This also means that the previous view in the clock view (when the next alarm will ring) has to be removed
3. **Stopwatch**: Should show in the notification bar of Android what the current state of the stopwatch is, including buttons for pause/start, lap and reset (currently no display in the notification bar)
4. **Timer**: Should show in the notification bar of Android what the current state of the timer is, including buttons for pause/start and reset (currently only showing how long you have set the timer per default)

### Bug:
1. **Alarm**: Since version 5.4.0 the selected song is played twice with a delay of about 1 second when the alarm is ringing
2. **Alarm**: Assuming it is 18:20 o´clock and you set the alarm to 18:21 o´clock (Today) without specifying a specific day, turn off the screen of your smartphone, wait until the alarm rings, go back to the App at 18:22 o´clock and you will see that the same alarm is still active (slider is "On") and it still says "Today" -> Expectation: It should be deactivated (since it is only set once) and it should not say "Today"
3. **Alarm**: Set alarm WITHOUT setting a specific day, it will ring sometimes only, when I press the power button on my smartphone to turn on the screen
4. **Alarm**: If you have several active alarms and set the slider of one of them to "On" or "Off", the popup that appears briefly below sometimes does not show the correct remaining time and sometimes a separate popup for each active alarm appears, even though only one slider was set to "On" or "Off"
5. **Stopwatch**: Stopwatch stops running when you close the App via the Android navigation bar (□-icon and swipe the App away) -> Displays "0.0" again after reopening the App
6. **Timer**: Timer will be killed in the background if you close the App directly from the App very fast via the Android navigation bar (□-icon and swipe the App away within 1 sec.) while the timer is still running -> If you do it slower (just press □-icon), the timer icon will first appear in the notification bar of Android and then you can swipe away the App and the timer will still run when you start the App again -> That means it really only happens when you do it fast!
7. **Timer**: Timer icon in the notification bar of Android should only appear if you have started the timer and not if you just open the App and then return to the home screen via the ◯-icon in the Android navigation bar

**Comment by tibbi** [comment]
Hey, report issues one by one please, such tickets cannot be maintained.
