### ISSUE TITLE
[Feature Request] Alarm: Show remaining time permanently per alarm

### ISSUE THREAD

**Issue by Asiaboy89** [SimpleMobileTools/Simple-Clock#239]
Regarding #237

Device: Honor 10 (Build number: 10.0.0.180(C432E5R1P4patch01), EMUI Version: 10.0.0, Android Version: 10)
Simple-Clock App Version: 5.4.0

### Feature Request
Alarm: Permanently show PER alarm, how much time will remain until the next setted alarm will ring (currently only shown in a 3-second popup at the bottom when the alarm is activated) -> This also means that the previous view in the clock view (when the next alarm will ring) has to be removed

**Comment by tibbi** [comment]
that isnt planned
