### ISSUE TITLE
Alarm does not ring

### ISSUE THREAD

**Issue by yerar** [SimpleMobileTools/Simple-Clock#24]
#**Expected behavior**

After setting up an alarm, it is expected that at certain time it has to sound.

**Actual behavior**

When the alarm is supposed to sound, it only shows the alarm notification/layout and it does not make any sound.  

Alarm volume is on its max value and power optimization is disabled for the app.
   
Version: 3.1.1
Operating system:
    Android: 8.0.0
    OxygenOS: 5.0.4

**Comment by x-jokay** [comment]
Can confirm this for version 3.1.2 and Android 8.0.0 aswell.

**Comment by arturbosch** [comment]
Thanks it works now!

**Comment by x-jokay** [comment]
Thx for the fix :)
