### ISSUE TITLE
[Bug] Alarm: One-Time-Alarm is still active

### ISSUE THREAD

**Issue by Asiaboy89** [SimpleMobileTools/Simple-Clock#243]
Regarding #237

Device: Honor 10 (Build number: 10.0.0.180(C432E5R1P4patch01), EMUI Version: 10.0.0, Android Version: 10)
Simple-Clock App Version: 5.4.0

### Bug
Alarm: Assuming it is 18:20 o´clock and you set the alarm to 18:21 o´clock (Today) without specifying a specific day, turn off the screen of your smartphone, wait until the alarm rings, go back to the App at 18:22 o´clock and you will see that the same alarm is still active (slider is "On") and it still says "Today" -> Expectation: It should be deactivated (since it is only set once) and it should not say "Today"

**Comment by tibbi** [comment]
just restart the app then
