### ISSUE TITLE
[Bug] Alarm: One-Time-Alarm is ringing only sometimes when I turn on my screen

### ISSUE THREAD

**Issue by Asiaboy89** [SimpleMobileTools/Simple-Clock#244]
Regarding #237

Device: Honor 10 (Build number: 10.0.0.180(C432E5R1P4patch01), EMUI Version: 10.0.0, Android Version: 10)
Simple-Clock App Version: 5.4.0

### Bug
Alarm: Set alarm WITHOUT setting a specific day, it will ring sometimes only, when I press the power button on my smartphone to turn on the screen

**Comment by tibbi** [comment]
that is a device issue, check your battery and reminder settings
