### ISSUE TITLE
[Bug] Alarm: Popup for remaining time displays wrong values sometimes

### ISSUE THREAD

**Issue by Asiaboy89** [SimpleMobileTools/Simple-Clock#245]
Regarding #237

Device: Honor 10 (Build number: 10.0.0.180(C432E5R1P4patch01), EMUI Version: 10.0.0, Android Version: 10)
Simple-Clock App Version: 5.4.0

### Bug
Alarm: If you have several active alarms and set the slider of one of them to "On" or "Off", the popup that appears briefly below sometimes does not show the correct remaining time and sometimes a separate popup for each active alarm appears, even though only one slider was set to "On" or "Off"

**Comment by tibbi** [comment]
should be solved already
