### ISSUE TITLE
It is not possible to switch on one-off alarm for the current day

### ISSUE THREAD

**Issue by eandersons** [SimpleMobileTools/Simple-Clock#251]
It is not possible to set one-off alarm for the current day. For example, if I am going to sleep at 2 AM (02:00) and want to wake up at 7 AM (07:00), it is not possible to set alarm as one-off alarms are automatically scheduled for the next day. I think that that it would be more convenient if the alarm would go off at the next time occurence.

**Comment by tibbi** [comment]
arent you confusing am/pm? It should be possible just fine.

**Comment by eandersons** [comment]
I am using 24 hour clock. I used AM in the issue description to clearer illustrate the example.

I just checked again and everything seems to be fine indeed.
I paid attention to this because one night I set an alarm for morning and I saw in the notification bubble that the remaining time is 1 day, x minutes, x seconds. Maybe I was too tired and saw what was not there. 😃

Closing for now.

**Comment by eandersons** [comment]
Reopening as the real issue regarding this is when an existing one-off alarm is simply turned on, as it seems that existing these kind of alarms at midnight are automatically rescheduled for the next day.

The updated example. There is an one-time alarm set at 07:00. It was used before and it was turned off after. If one turns it on after the midnight but before the set time, this alarm is set to go off not at 07:00 on the current day but on the next one.

**Comment by palianskas** [comment]
I can confirm that the described erroneous behaviour is present . Instead of waiting a day I set the system time a little less than 24 hours in the future however, this might possibly interfere to some extent.

**Comment by ltGuillaume** [comment]
Ouch, just saw this, too. This is a big one. I could really see people not waking up because of this.

**Comment by tibbi** [comment]
should be doable already
