### ISSUE TITLE
Alarm icon with time is always displayed even with there is no alarm set

### ISSUE THREAD

**Issue by modestderp** [SimpleMobileTools/Simple-Clock#252]
In the clock widget and in the "Clock" tab of the app (not sure the correct name, just the most left-hand side tab), I noticed that a line for alarm with the alarm icon and a random time is always displayed. This happens even if I don't have a alarm set. If I do have an alarm set, the displayed time does NOT match with that of the alarm.

Basically I always see something like this:
First line: Current time
Second line: Date and day of week
Third line: Alarm icon with a random time that appears out of nowhere (with or without alarm set)

**Comment by tibbi** [comment]
dont you have some alarm set in an other app either?

**Comment by modestderp** [comment]
> dont you have some alarm set in an other app either?

That was the first thing I checked, no alarms set in other clock apps that I had either.

Two observations that I didn't mention:

1. The alarm seems to be able to update to a future date time. So it seems like there is an active alarm somewhere, but after searching through relevant apps I couldn't find any.

2. When I reboot my phone and everything is initializing no alarm was displayed in the widget. When everything has started, the alarm pops up.

**Comment by tibbi** [comment]
try disabling all clock/alarm apps, then by enabling one by one figure out which is causing the issue

**Comment by modestderp** [comment]
I've uninstalled all clock/alarm apps (except for the ones that I can't unless I root), and seems no effect on current situation. The ones I can't uninstalled I've made sure that there are no alarms set in the app.

**Comment by modestderp** [comment]
If no one else is reporting such issues, I guess I will close this.
