### ISSUE TITLE
Can you guys remove the header bar ?

### ISSUE THREAD

**Issue by moshiur-raj** [SimpleMobileTools/Simple-Clock#253]
The header bar is really not necessary for the clocks app. It just takes up extra space and having the application bar? right below it makes the app look bad. It would be great if you guys removed the header bar and put the application bar at the bottom of the screen for better navigation.

**Comment by tibbi** [comment]
Not really, I dont like removing such elements unnecessarily.

**Comment by moshiur-raj** [comment]
Understandable. Can you put the application bar(the one that shows which tab you're at, I really have no idea what it's called) at the bottom then ?
It would really improve the look imo.

![Screenshot_20201214-154446_new](https://user-images.githubusercontent.com/36466700/102066848-88374380-3e24-11eb-9208-25f4b0422b72.png)

**Comment by tibbi** [comment]
moving tabs at the bottom is on the roadmap as part of some redesigning, not sure when will I get to it. It will affect all apps with tabs
