### ISSUE TITLE
Timer: Sound and vibrate options don't work properly on Android 7

### ISSUE THREAD

**Issue by voussoir** [SimpleMobileTools/Simple-Clock#256]
Hi, thank you for your software.

I have two devices: LG G8X running Android 10, LG K10 running 7.0. Both are using Simple Clock 5.4.0 downloaded from F-Droid. I'm having a few issues with the timer settings:

- Android 7: The vibration slider does not work. If the phone is in sound or vibrate mode, the timer always vibrates, even with the slider off. If the phone is in silent mode, the timer never vibrates, even with the slider on.
- Android 7: When I set the ringtone to "no sound" it rings anyway. In my case it is defaulting to a tone called "Windflower". This happens to be the alphabetically-last ringtone on the available list, which may be relevant to the code bug?

I understand that Android's APIs for fine-tuned vibration and sound control have probably changed over the years, so it may not be possible to control these features properly in Android 7. In that case, I would suggest the vibrate slider be hidden, and the "no sound" option be removed when the user's device is one of these less-featured versions.

- Android 10: When the phone is in silent mode, the timer does not vibrate even with the slider on.

I'm not sure if this is an OS limitation. I also can see room for debate as to whether the timer should obey the system's volume silent mode or the timer's settings. I think it should follow the timer settings even if the phone is on silent.

(On Android 10, the "no sound" option works properly)

Let me know if I can add any other detail. Thanks!

**Comment by tibbi** [comment]
such things should be handled by the system, not us. Especially on Android 8+ you can customize notification streams, like what audio should be played, or when should it vibrate.

**Comment by voussoir** [comment]
Well, yes, I agree. That's why I was suggesting that if the user's device doesn't follow Simple Clock's options, they could be hidden from the UI. Otherwise the experience is somewhat incongruous.

**Comment by voussoir** [comment]
For what it's worth, I have experience with some apps that allow some notifications to vibrate and some notifications don't -- even though Android 7 doesn't have the fine-grained notification control that later versions do. In particular I use Zoho's email app with multiple accounts, some vibrate and some don't. I believe it requires the app to open multiple notification channels with different settings and sending the notifications down the right one for the event.

Just throwing it out there.

**Comment by buliasz** [comment]
> such things should be handled by the system, not us

Well, this is not always proper approach. I have the same issue on Galaxy S7 (Android 8) and probably many others have it too. When I choose "No sound" (wanting only vibration) I still get the sound. Other applications I've tested deal with it somehow and work properly.
