### ISSUE TITLE
[BUG] A toast telling remaining time is shown when alarm toggled off

### ISSUE THREAD

**Issue by teemue** [SimpleMobileTools/Simple-Clock#262]
I believe this toast notification is not intended: when toggling off an alarm, toast is shown, telling remaining time until just-disabled alarm would have gone off. It's the same notification when toggling an alarm on.

**Comment by tibbi** [comment]
I cannot reproduce it, what app version are you using? Does it always happen, even at toggling the alarm from the app itself?

**Comment by teemue** [comment]
Version is 5.5.0. Happens in the app.

https://user-images.githubusercontent.com/317905/107153790-03762b00-6978-11eb-8089-441977326f0c.mp4

**Comment by tibbi** [comment]
and if you enable it, does it show too? Does the alarm itself work well, I mean if enabled? Or it is flipped?

**Comment by teemue** [comment]
Yes, everything else work as expected. However, I found this buggy behaviour doesnt occur always,very hard to figure out precise way to reproduce...

**Comment by ltGuillaume** [comment]
Same here, but it only happens with __nonrecurring alarms set to go off today__.

LineageOS 17.1 (Android 10)

**Comment by tibbi** [comment]
should have been resolved already
