### ISSUE TITLE
time to wakeup call on day of summertime switch

### ISSUE THREAD

**Issue by dietmarczekay** [SimpleMobileTools/Simple-Clock#266]
the calculation did not recognize the 1 hour shift for the night clocks set to summertime (and maybe the day back to normal time)

**Comment by BlizzardWizzard** [comment]
> the calculation did not recognize the 1 hour shift for the night clocks set to summertime (and maybe the day back to normal time)

Yup, also doesn't work when it's set back to normal time... got woken up an hour early today.

**Comment by tibbi** [comment]
duplicate of #131
