### ISSUE TITLE
[Bug] Timer Sound Killed When Hitting Power or Volume Buttons

### ISSUE THREAD

**Issue by seniorm0ment** [SimpleMobileTools/Simple-Clock#269]
The notification tone to the timer dies immediately upon pressing the power button, or volume buttons. I understand if this isn't a bug but a feature, however if that is so the option to ignore power and volume presses would be nice.

I assume it's understandable accidentally pressing these buttons happen, so an option to only allow it by opening the app and stopping, or from the notification bar would be nice.

Not sure if this is an issue with the alarm clock, but if so then this apllies to that as well.

**Comment by tibbi** [comment]
I dont really plan changing it, seems like it is handled by the system
