### ISSUE TITLE
Option for stop watch: unpause starts new lap

### ISSUE THREAD

**Issue by hcgrove** [SimpleMobileTools/Simple-Clock#279]
When I use the stop watch, I always take a short break between "laps", so I always have to press two buttons when I start a new lap. It would be great if there was an option to combine those two actions into one button press.

**Comment by tibbi** [comment]
I dont really plan adding any extra button, just press Lap and Pause for now. Too many buttons would make it confusing.

**Comment by hcgrove** [comment]
I wasn't thinking of a new button, but a config option to make the Pause button also start a new lap.
