### ISSUE TITLE
Bug found on simple clock: App doesnt display full content while on landscape view

### ISSUE THREAD

**Issue by abdul-qudus** [SimpleMobileTools/Simple-Clock#30]
#### Expected behavior
While app is on landscape view. The content on the screen should be fully displayed or scrollable.

#### Actual behavior
Using landscape on that aspect of the app some features could not be accessed.

#### How to reproduce
Download Simple clock on fdriod. 
Launch app and go to the timer tab option. Turn device auto rotate, then the vibration option and ringing tone wont be displayed.

* Application: simple clock. version 3.1.1
* Operating system: andriod 7.0, tecno wx3p

#### Recording Of The Bug
![videotogif_2018.03.16_12.04.31.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521593513/adez2fami6hwcmiyczkk.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@abdulqudus/bug-found-on-simple-clock-app-doesnt-display-full-content-while-on-landscape-view">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by ChiefMikeK** [comment]
https://user-images.githubusercontent.com/20070053/38229106-a126592a-3739-11e8-8297-e72c8ea0ac4d.png
Also hiding alarms on/off button
ref #34 closed

**Comment by tibbi** [comment]
it will never display everything properly, I dont plan optimizing for small landscape displays. It isnt worth it.
