### ISSUE TITLE
Sort timers

### ISSUE THREAD

**Issue by morfikov** [SimpleMobileTools/Simple-Clock#307]
Currently it looks like the timers in the second tab in Simple Clock are sorted by the time they were added. So instead of having

```
07:30
08:00
10:20
```

we have 

```
10:20
07:30
08:00
```

It would be nice to sort them out because when you have many timers, finding the right one in such mess takes time.

**Comment by tibbi** [comment]
you can change sorting with the top menu button

**Comment by morfikov** [comment]
Oh I see. Thanks for the info.
