### ISSUE TITLE
Improve alarm label

### ISSUE THREAD

**Issue by Aga-C** [SimpleMobileTools/Simple-Clock#315]
Hi,

Currently, the alarm label is in the same font size and color as the text for repeating days above it (see the screenshot). It would be nice to highlight it somehow, so this different texts wouldn't look the same. Thanks!

![image](https://user-images.githubusercontent.com/85929121/143678711-8ac13f21-e558-4406-997e-207b0098f3de.png)

**Comment by tibbi** [comment]
seems good to me, will keep an eye on it for the future
