### ISSUE TITLE
Widget: Hide "a.m." and "p.m." in 12 hour mode

### ISSUE THREAD

**Issue by cyrildtm** [SimpleMobileTools/Simple-Clock#317]
Thank you for making this possible! I love that the widget uses my custom font which is much thicker and easier to read. 

Feature request: Remove the "a.m." and "p.m." text in widget attached to the 12 hour format time, so the actual time numbers are centered and large. I can tell if it's morning or afternoon by other means. 

At present, with 12 hour format, I see the numbers and the letters in one row: 

![widget-12hr](https://user-images.githubusercontent.com/5927301/144708588-b4063594-ae1b-4116-bf1c-12e4e0d988df.png)

But half of my screen is used to display information I already know, and the numbers are too little for me to read at a distance. 

Usually I set it to 24 hour format, so the numbers are big, and it's really easy to recognize time at a glance, like this: 

![widget-24hr](https://user-images.githubusercontent.com/5927301/144708637-b1b3db50-5190-4627-9552-9e9510a6befe.png)

But with 24 hour format, the hour number either has a zero in the front or it's too large value (>12) not what I'm willing to deal with.

**Comment by tibbi** [comment]
I dont really want to hide that, sounds weird

**Comment by cyrildtm** [comment]
> I dont really want to hide that, sounds weird

:/ It's not weird to me at all. My clock has this format since the beginning, and when people ask me time, I read them 12 hour format numbers without mentioning am or pm at all. 

Just so you know what I'm talking about, here's a comparison between the stock app from LOS 18.1 (top) and yours (bottom). The navigation bar clock on top left is customizable on my phone. In the past I leave a small size AM/PM sign when I have a full-screen phone. Now that I have a new phone with a notch, I have to save some space by hiding that information. 

But I can definitely tell whether it's AM or PM by looking elsewhere, even before I read the screen. 

![compare](https://user-images.githubusercontent.com/5927301/144728120-09161f2d-4f92-4624-a77d-b9be8d3c689f.png)

Well, your response is fast, I would give you that. Thank you for making many tools that I have been happily paid for though, but I'm probably gonna look for substitutes now.
