### ISSUE TITLE
Issues with alarm sounds and vibrations

### ISSUE THREAD

**Issue by morfikov** [SimpleMobileTools/Simple-Clock#321]
I recently moved to AOSP based ROM (A11) and I installed Simple Clock there. It looks like it has the following issues on my phone:

- when the default ringtone is left untouched, Simple Clock plays it only once instead of looping the sound.
- when the ringtone is set manually, Simple Clock plays both of the sounds at the same time -- the default ringtone set in the system and the one set in Simple Clock. The ringtone that is set as default in the system is being played once, and the ringtone set in Simple Clock is being looped, which gives really annoying effect for the first few seconds.
- when the Vibrate option is checked, the phone doesn't vibrate. 

I installed the Google's Clock from GPlay, and it looks like that this app plays sounds as expected and also the vibration works without issues.

I tried to uninstall and reinstall Simple Clock, but without any luck. 

I use 5.6.1 version of Simple Clock from F-Droid.  

In logcat, the following messages can be observed when the alarm fires (if that helps in anything):

```
12-22 07:39:00.936 31356 31356 W MediaPlayer: Use of stream types is deprecated for operations other than volume control
12-22 07:39:00.937 31356 31356 W MediaPlayer: See the documentation of setAudioStreamType() for what to use instead with android.media.AudioAttributes to qualify your playback use case
12-22 07:39:01.020 31356 31356 D EventBus: No subscribers registered for event class p3.b
12-22 07:39:01.020 31356 31356 D EventBus: No subscribers registered for event class x4.h
```

**Comment by tibbi** [comment]
this app has recently been abandoned already because the inability to make it work reliably enough, you should just use some other app

**Comment by morfikov** [comment]
I see, too bad.
