### ISSUE TITLE
Graphical glitch shows alarm as on when it is off

### ISSUE THREAD

**Issue by pauleonix** [SimpleMobileTools/Simple-Clock#323]
My alarm clock did not ring even though the switch was looking right. When I touched it, it switched to "off" graphically, but showed the message about the number of hours until the next alarm as if I turned it on. After touching the switch a third time, graphics and functionality seem to be realigned (it showed the message again and now the alarm shows below the main clock, it did not show there at the start).

**Comment by malick-2892** [comment]
Could be related to my issue report I'm sensing.
https://github.com/SimpleMobileTools/Simple-Clock/issues/324

**Comment by tibbi** [comment]
sholud be working better in 5.7.0 with checkboxes and other changes
