### ISSUE TITLE
RFC. Introduce skins.

### ISSUE THREAD

**Issue by malick-2892** [SimpleMobileTools/Simple-Clock#325]
Hi SMT Devs!
Is there a chance to have Clock (or any other app from the family for that matter) be skinnable (plugins?). It occured to me once one of my alarm switches has been covered with "+" button and I couldn't switch that one off/on. That way independent devs, or yourselves might apply different looks to the apps, should You allow appropriate API for skins/plugins.
Regards!

**Comment by malick-2892** [comment]
I just learned the app has been retired, so my request is only partial. It may still apply to the rest of the SMT apps family.

**Comment by tibbi** [comment]
some styling things will be added soon, just like in other apps
