### ISSUE TITLE
The city time is hidden by the "Add" button in landscape view

### ISSUE THREAD

**Issue by MrLent** [SimpleMobileTools/Simple-Clock#34]
When there are at least one city added to the main time, the "Add" button hide the added cities time in landscape view.

Application version 3.1.1 installed with F-Droid on Android 7.0 on Moto G4.

**Comment by tibbi** [comment]
child of #30

**Comment by ChiefMikeK** [comment]
Suggestions make **add button** _smaller_ so as not to block text or alarm switches
![screenshot_20180403-113145](https://user-images.githubusercontent.com/20070053/38229106-a126592a-3739-11e8-8297-e72c8ea0ac4d.png)
then move up and left 15-20px see screenshot.
