### ISSUE TITLE
White bar on the bottom of all Simple apps

### ISSUE THREAD

**Issue by candroid-man** [SimpleMobileTools/Simple-Clock#340]
![Screenshot_20220505-024819.png](https://user-images.githubusercontent.com/51019003/166881923-51b4dcba-1e70-4cc3-aac0-5acb5b258d7a.png)

As you can see this looks awful! This screenshot was taken on the Pixel 6 Pro. If there is a way to make the home bar thing overlap the body of the app it would make them look much better

**Comment by tibbi** [comment]
report it at the General-Discussion repo please as it affects all apps. I guess you enabled navigation by gestures?
