### ISSUE TITLE
Some formatting changes for the clock widget

### ISSUE THREAD

**Issue by nemoskapetanos** [SimpleMobileTools/Simple-Clock#342]
Hi Tibor,

Could you please add an option to centre the time inside the widget box. Also, could you shrink the font size of the AM/PM in the widget so it takes up less space & the actual time takes up more of the widget space. 

Otherwise, great app along with your other simple tools! 

Thanks!

**Comment by tibbi** [comment]
it is centered already, we cant change am/pm as it is now handled by the system. Else it wouldnt be reliable enough.

**Comment by nemoskapetanos** [comment]
That's a shame! Either way, thanks for a great app!
