### ISSUE TITLE
Date not update on widget

### ISSUE THREAD

**Issue by Altau38650** [SimpleMobileTools/Simple-Clock#343]
I would like to report 2 issues in the "Clock" application: a malfunction and a
language error.
The malfunction is that the date of the widget is not updated if you have not
been in the application.
The language error is that there should not be a comma between the day of the
month and the rest of the date. So today it says "Ven, 20 Mai" (in French) when
it should say "Ven 20 Mai".
That said, congratulations on your work and application.

**Comment by tibbi** [comment]
just upgrade to 5.7.x, the date updating has been fixed already. Some date format changing is on the roadmap, but it already reported somewhere else.

**Comment by Altau38650** [comment]
I run already the 5.7.0 version, the last update in Google Play.

**Comment by tibbi** [comment]
right, get 5.7.1, thats where the date has been fixed. Previously it was the time only.

**Comment by Altau38650** [comment]
Is this version avaiable on Google Play ?

**Comment by tibbi** [comment]
yes

**Comment by Altau38650** [comment]
No update possible in Google Play. I had to uninstall V 5.7.0 in order to install V 5.7.1

**Comment by Altau38650** [comment]
It's OK, it works now with the 5.7.1 version..
Thanks for the advice :)
