### ISSUE TITLE
Font size too big

### ISSUE THREAD

**Issue by dumblob** [SimpleMobileTools/Simple-Clock#348]
Font size is too big if the system font size is increased (e.g. on elderly phones):

![Screenshot_20220613-120135](https://user-images.githubusercontent.com/2451044/173331007-d514d662-122f-4874-adde-3c0d40645e25.jpg)

Potentially related: https://github.com/SimpleMobileTools/Simple-Clock/issues/110

**Comment by 27priyanshu** [comment]
Please assign this task to me.

**Comment by dumblob** [comment]
friendly ping @tibbi

**Comment by tibbi** [comment]
it has been resolved already
