### ISSUE TITLE
Sleep cycle calculator for alarms

### ISSUE THREAD

**Issue by balporig** [SimpleMobileTools/Simple-Clock#364]
Create next day alarm taking into account sleep cycles https://en.wikipedia.org/wiki/Sleep_cycle. The average sleep cycle is 90 min.

There are multiple ways this can be implemented:

- Second floating button above the `+` button with for e.g. moon icon. When clicked, it can show a popup dialog with a list of suggested alarms based on number of sleep cycles that can be selected. Example: https://play.google.com/store/apps/details?id=ru.olegfilimonov.sleeptime. `Configurable sleep cycle duration` in settings, with default 90 min.
- Using the same floating button as the previous idea. The dialog instead of listing alarms can calculate the alarm based on user input:  `number of cycles`, `cycle duration`, optional `desired wake time`
- be integrated in the normal alarm dialog, and so not to make it too cluttered with used tabbed navigation with a new tab implementing  either a list of suggested alarms or calculator dialog (same as described in the options with the floating button)
- probably more...

**Comment by tibbi** [comment]
that is way too advanced, dont expect having it here. Thanks though
