### ISSUE TITLE
Simple Clock "incompatible" with Nokia 6 2017

### ISSUE THREAD

**Issue by jakubcze12** [SimpleMobileTools/Simple-Clock#369]
When downloading Simple Clock through F-droid, it says it is "incompatible". When trying to install the APK through a computer using `adb install com.simplemobiletools.clock_29.apk`, it also gives an error:

```
jacob@main ~/debloat $ adb install files/com.simplemobiletools.clock_29.apk 
Performing Streamed Install
adb: failed to install files/com.simplemobiletools.clock_29.apk: Failure [INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl717413532.tmp/base.apk (at Binary XML file line #7): Requires newer sdk version #29 (current version is #28)]
```
I was able to install older versions of simple clock normally. Also all of the other simple apps work and install fine.

Device: Nokia 6 2017
OS version: Android 9

**Comment by tibbi** [comment]
the minimal required OS version has been increased to 10
