### ISSUE TITLE
Timer notification is persistently shown even if sleep mode

### ISSUE THREAD

**Issue by quazgar** [SimpleMobileTools/Simple-Clock#372]
## Problem ##

When a timer is running, the notification is persistently shown on the screen, even after I turn off the phone. This probably drains the battery a lot.

## Further remarks ##

It looks like the displaying is triggered every time the remaining time is updated: when I wipe the notification away, it is not shown again immediately, but it takes about a second to reappear.

While it may make sense to notify the user about running timers, other apps solve this by showing the current status only every now and then (say every 15 minutes).

## Versions ##

Simple Clock: 5.8.1 (via F-Droid)
Android 10

**Comment by tibbi** [comment]
it works as expected, I dont want to hide running timers

**Comment by quazgar** [comment]
Showing the timer I completely understand, but waking up the phone every second even after I press the power button  is another thing. It is free software though (although I bought the "support-the-author version" for some of your apps), so up to you to decide.

**Comment by bergentroll** [comment]
I use 30 min timer and have no need to control it. Just want a «ding» after time is gone. Have no idea why to have lighting screen and draining battery obligatory.
