### ISSUE TITLE
App icon inconsistencies.

### ISSUE THREAD

**Issue by BrendonIrwan** [SimpleMobileTools/Simple-Clock#375]
This applies to all of Simple Mobile Tools but I'm writing it here only.

This is what your application icons look like in F-Droid:

![icons](https://user-images.githubusercontent.com/13151306/181840005-15b2bcfa-46a6-4aa5-bf19-6be6c44196d5.png)

Some are square (correct to my setting), some are not.

Also, my launcher is set to "prefer icons meant for Android 7.1 or lower", and that too caused some inconsistencies.

If you have time to unify the icon behavior throughout the suite then it'll be great.

**Comment by tibbi** [comment]
it should be square in every app once they get updated
