### ISSUE TITLE
Upload release 5.6.1 to F-Droid for older Android versions?

### ISSUE THREAD

**Issue by psisquared2** [SimpleMobileTools/Simple-Clock#382]
Hey,
first of all, I love your apps and I have donated for your Gallery app before. Today I tried to install the Clock app on an old Android phone, but couldn't download it from F-Droid as all available versions require Android 10 or newer. Going through all releases on Github to find the most recent one for Android 5 was possible, but a bit cumbersome. Would it be possible to upload release 5.6.1 to F-Droid, maybe with a note that the version isn't supported anymore?
Thanks and kind regards!

**Comment by tibbi** [comment]
Not really, I dont plan lowering the required OS version.
