### ISSUE TITLE
Android 8 no longer supported?

### ISSUE THREAD

**Issue by Krzmbrzl** [SimpleMobileTools/Simple-Clock#385]
I used to have this app installed on my phone but since the last (or one of the last) update(s) I was unable to update the app via F-Droid. The update always failed.

Now I tried to uninstall the app in order to perform a clean re-install, but now F-Droid is claiming that there was no version of this app that is compatible with my device (running Android 8).

Was this an intentional decision to drop support for this Android version? If so, why? 👀

**Comment by tibbi** [comment]
it was intentional to not having to mess with lower OS versions as there are many different restrictions.
