### ISSUE TITLE
Can timers come through alarm sound?

### ISSUE THREAD

**Issue by Raj2032** [SimpleMobileTools/Simple-Clock#399]
Currently timer alarms don't come through alarm sound and I keep on ending up missing timers as I put my phone on vibrate, is it possible to have an option for timers to use the alarm sound profile?

**Comment by tibbi** [comment]
you should be able to customize it in the app or device settings, depends on your OS version

**Comment by Raj2032** [comment]
@tibbi

> you should be able to customize it in the app

Can't seem to find the setting there unless if I am missing something?

> device settings, depends on your OS version

I went to app info -> notifications -> And I have "Alarm" and then various "Timer".

![image](https://user-images.githubusercontent.com/29293830/193455465-86a2957c-4073-4181-9ae4-609b257d61ff.png)


it appears that everytime I add a timer (in the app) then over here it adds more "Timer". Not too sure why it can't be set to one Timer rather than adding more "Timer" over here?

**Comment by tibbi** [comment]
will keep an eye on it then

**Comment by Raj2032** [comment]
@tibbi Ok thank you, in the mean time can you tell me where are all the sounds kept cause currently as you can see at the 2nd level you can see Timer is set to "silent" so not too sure where it is located at?

**Comment by tibbi** [comment]
every timer can have its own audio, you see it at the dialog where you are changing the duration

**Comment by Raj2032** [comment]
@tibbi Over here:

![image](https://user-images.githubusercontent.com/29293830/193456635-7fd2cb9a-e436-4152-9ed5-f789c3019f27.png)


Each sound is coming from a particular folder/location, where is the location, not the name of the sound, I just need to know the location of where all the audio files of the alarm sounds are kept?

**Comment by Raj2032** [comment]
@tibbi 

![image](https://user-images.githubusercontent.com/29293830/193456866-20ec225e-102d-4800-b07a-2e0f57bca923.png)

Its set to Basic Bell sound yet no sound comes through.

If I go to Timer

![image](https://user-images.githubusercontent.com/29293830/193456893-0a6f3983-88b6-40ca-b496-c7fe7ebb0b8a.png)


It doesn't seem to come through alarm sound, its coming through as notification sounds, what I want is a setting that goes through alarm sounds.

This is what I am talking about

![image](https://user-images.githubusercontent.com/29293830/193457182-80377dc8-e687-4077-96c0-a57bb1e6e2af.png)

Only Alarms go through alarm volumn, not timer alarms.

**Comment by Raj2032** [comment]
@tibbi Hi, unfortunately I have had to make the decision to uninstall simple clock and replace it with another app until a resolution is provided as I am unable to use the timer functionality correctly.
