### ISSUE TITLE
[Feature Request] Timer: Option to maximize a timer

### ISSUE THREAD

**Issue by hasezoey** [SimpleMobileTools/Simple-Clock#402]
I would like to request a way / option to maximize a single timer so to not accidentally start / cancel another time and to have a simple way to start / stop / view a specific timer (for example when cooking)

<details>
<summary>Example of Google's Clock app with timer maximized</summary>

(image pulled from the play-store)
![google_timer](https://user-images.githubusercontent.com/10911626/197197736-467cdd81-41a2-4a98-b106-c5ba4c561f74.png)

</details>

could be implemented like the google app, so you could toggle between views* or only maximize one
*with that way, like the google app you could maybe scroll through other timers by swiping up/down (or maybe a toggle left/right)

**Comment by tibbi** [comment]
that isnt really on the roadmap
