### ISSUE TITLE
Time remaining message behaviour

### ISSUE THREAD

**Issue by Pablohn26** [SimpleMobileTools/Simple-Clock#406]
Hi,

I do not know if this is a bug or a feature, but I attach a video where you can see the time remaining message blinking several times when you enable and disable an alarm several times.

https://user-images.githubusercontent.com/1228418/197740671-d0746a91-979c-4d61-8c21-2b10978741c3.mp4

Would be good do not show so many messages that show always the same

**Comment by tibbi** [comment]
of course it shows it multiple times if you toggle it multiple times..
