### ISSUE TITLE
[Feature request] add option to not show how far in the future an alarm is

### ISSUE THREAD

**Issue by KCGD** [SimpleMobileTools/Simple-Clock#417]
As a college student, I frequently use this app as an alarm clock (and it works really well!). 

However, it would be nice to have an option to disable the popup saying "alarm set for x hours y minutes from now". I'd rather not know how little sleep I'm getting. 

Please consider adding this.

**Comment by tibbi** [comment]
I want to keep it as a security check to avoid mistakes
