### ISSUE TITLE
observation : Simple Clock widget shows android clock alarms

### ISSUE THREAD

**Issue by GuitarBilly** [SimpleMobileTools/Simple-Clock#43]
just an observation as I have both stock Android clock and Simple Clock (SC) widgets on my phone.

When i create an alarm in stock Android clock and it is soonest it is shown in both widgets as the next upcoming alarm.
When i create an alarm in Simple Clock and it is soonest it is shown in the SC widget but not in the stock Android clock widget.

So it seems SC is aware of all alarms and stock Android clock is only aware of its own app alarm.

**Comment by tibbi** [comment]
that seems like an issue on their end, as they dont update the widget properly. Can you try recreating the stock alarms widget, if it picks up the proper alarm?

**Comment by GuitarBilly** [comment]
Tried that. No update. For me no issue as i would like to use Simple Clock widget only!

My main goal was to raise awareness and prevent future SC issues due to non standard or incompatible items being used or something.

p.s. this is only the stock widget, the (system?) notification bar is always updated correctly to the next upcoming alarm no matter if it is made with stock Android clock and/or Simple Clock.

**Comment by tibbi** [comment]
that particular alarm is shared within the whole system, so each app sees the same ones. Maybe you can try downloading a couple other clock apps, but Im pretty sure that the issue is at the built in one.

**Comment by tibbi** [comment]
so I guess it is a system issue, stock apps are usually trash
