### ISSUE TITLE
[Feature request] Random files from a specific folder 

### ISSUE THREAD

**Issue by Primokorn** [SimpleMobileTools/Simple-Clock#430]
Hello,
Always using the same ringtone doesn't help to wake up 😂
Could you please consider adding a feature where the app plays a random files from a specific folder?
Thank you.

**Comment by tibbi** [comment]
that isnt really on the roadmap

**Comment by Primokorn** [comment]
@tibbi can we see the road map? No matter the app you don't accept feature request if it's not on the road map?

**Comment by tibbi** [comment]
it isnt written down anywhere

**Comment by Primokorn** [comment]
Is it a real answer? I was going to support your work...

**Comment by ShadyMedic** [comment]
Please, I'd love to have this feature as well 🥺
