### ISSUE TITLE
Alarm groups (similar to appointment groups in simple calendar)

### ISSUE THREAD

**Issue by Markus-N** [SimpleMobileTools/Simple-Clock#431]
I'm using a lot of alarms during working days. One for getting up (monday, tuesday, thursday, friday) another one for getting up on wednesday and some more to remind me of the first video meeting per day (time is different almost every day of week).  
When I'm vacationing, I have to disable then all individually.

It would be nice to group them and disable the whole group at once. I would then have a second group for my vacation alarms, and maybe a third one for independent alarms.

**Comment by tibbi** [comment]
dont really expect having that, it is way too advanced
