### ISSUE TITLE
[Feature Request] Improve behavior of Simple-Clock after an alarm went off

### ISSUE THREAD

**Issue by basings** [SimpleMobileTools/Simple-Clock#435]
### Behavior:

After turning off an alarm from Simple-Clock, the app, specifically the alarm ringing screen, appears as the last opened app. If you then switch to the last used app (which is very common nowadays), the alarm goes off again.

### Solution:

It would be best if Simple-Clock would be removed from the recent app list (like the launcher), but only after an alarm went off, not always. As an alternative go into another (main?) window and not the alarm window.

**Comment by pudup** [comment]
Currently my only problem with this app. Can accidentally set off full volume alarms through the recents menu.
