### ISSUE TITLE
[Feature Request] Darken the main background window when setting an alarm or timer 

### ISSUE THREAD

**Issue by basings** [SimpleMobileTools/Simple-Clock#436]
### Behavior: 

When setting or modfying an alarm or timer there is no visual difference between the foreground window and the background window. The  window has no border and the background color is the same which makes it very difficult to distinguish between foreground and background information. 

Following is the actual screenshot I took on my phone (GrapheneOS, Android 13). When I took the screenshot the background darkened automatically. 

![Screenshot](https://user-images.githubusercontent.com/92867705/221377057-0827aa32-0c98-45c0-b24f-655381d7df6d.jpeg)

Following is a colored screenshot which shows the actual screen you would usually see (when not taking a screenshot).

![Screenshot2](https://user-images.githubusercontent.com/92867705/221377204-4c2d713e-d145-4bf9-957d-0a5c9675df1f.jpeg)

### Solution: 

Darken the main background window when setting an alarm or timer, basically whenever a smaller window covers the main window

**Comment by basings** [comment]
The "Sort by" window in alarm has the same problem.

**Comment by tibbi** [comment]
it seems to work just fine to me

**Comment by basings** [comment]
Then it's a bug.

Version 5.10.0

com.simplemobiletools.clock
versionCode 36

targetSdk 33
minSdk 23

 -   Pixel 6
  -  Android 13
   - GrapheneOS

**Comment by basings** [comment]
You can circumvent this behavior by setting theme to "material you"
