### ISSUE TITLE
[Feature Request] Make App findable as "Simple Clock"

### ISSUE THREAD

**Issue by basings** [SimpleMobileTools/Simple-Clock#437]
### Current Behavior

Currently, you can only find the app by searching for "Clock" and not "Simple Clock" or "Simple".

### Solution

Add "Simple" to the name that's searchable within a launcher to quickly find Simple Apps.

**Comment by tibbi** [comment]
that is expected

**Comment by basings** [comment]
Then it's a bug. 

Version 5.10.0

com.simplemobiletools.clock
versionCode 36

targetSdk 33
minSdk 23

- Pixel 6
- Android 13
- GrapheneOS
- bug appears on GrapheneOS Launcher, Kvaesito, Nova
