### ISSUE TITLE
Leading 0 in 24h mode.

### ISSUE THREAD

**Issue by BoBeR182** [SimpleMobileTools/Simple-Clock#440]
![Screenshot_20230308-020257_Trebuchet](https://user-images.githubusercontent.com/525433/223642237-763f3e68-49e3-486c-98a2-e3c710c47bae.png)
Please add leading 0 in widget in 24h mode.

**Comment by tibbi** [comment]
that time is handled by the system, not us

**Comment by BoBeR182** [comment]
No it's handled by the app, system returns correct time when added as a secondary timezone clock.
Please reinvestigate and reopen.
![Screenshot_20230623-000746_Clock](https://github.com/SimpleMobileTools/Simple-Clock/assets/525433/eae7ac89-022c-4934-953f-335ffe8b556d)

**Comment by tibbi** [comment]
you are mixing the widget and app...

**Comment by BoBeR182** [comment]
Both are missing a leading 0
