### ISSUE TITLE
Issues with overlapping sounds

### ISSUE THREAD

**Issue by PlayNowKnux** [SimpleMobileTools/Simple-Clock#445]
I used this alarm app this morning and noticed that the alarm sound was being played twice at the same time. I originally didn't know why it was happening, but when my second alarm went off (different sound) it played the sound that was assigned to it, but also my music that was paused in VLC. 

Because of this, I have come to the conclusion that the app plays paused music when the alarm goes off. 

Another issue I found is that when two alarms are set fairly close to each other (ex. One alarm is set for 6:05 and the other is set for 6:10), once the second alarm goes off, the sound doesn't stop for the first one, the sounds just play over each other.

**Comment by tibbi** [comment]
it is already reported somewhere
