### ISSUE TITLE
[Feature request] Option to set alarm for "tomorrow," which turns off when done

### ISSUE THREAD

**Issue by wdenton** [SimpleMobileTools/Simple-Clock#460]
Users will have regular alarms set up for their regular weekly schedule, but sometimes something special is happening tomorrow and they have to get up at  an unusual time and they want a special alarm just for that one day.  If tomorrow is Tuesday and a special alarm is set for Tuesday, then it will go off tomorrow, but then also want to go off Tuesday next week.  It would be a very nice if there was a way to set an alarm for tomorrow that would disable itself after it went off.

Thanks for a great clock app!

**Comment by tibbi** [comment]
if you uncheck all days, it will already trigger at the next possible time, likely tomorrow
