### ISSUE TITLE
Force alarm to headphones-only to not wake up other people

### ISSUE THREAD

**Issue by rice7th** [SimpleMobileTools/Simple-Clock#472]
Hello! Recently I've stumbled across this problem where I need to set the alarm very early in the morning without waking other people up. Unfortunately, even if I plug the headphones in, the alarm goes off both in the headphones AND the speakers, inevitably waking up everyone. I've found an old pr (#116 ) that was unfortunately closed since nobody requested it. As such, even if I am a _bit_ late, I am requesting said feature. The only other app I know is proprietary and sends a lot of data, so I was hoping that Simple Clock had that feature.

**Comment by tibbi** [comment]
that isnt really on the roadmap. And such things should be handled by the system anyway, not individual apps.

**Comment by rice7th** [comment]
@tibbi Well, even if it isn't on the roadmap this is a feature request, and unfortunately the system does not handle such things and rather let's the developer implement them
