### ISSUE TITLE
24 hour analog clock widget

### ISSUE THREAD

**Issue by goyalyashpal** [SimpleMobileTools/Simple-Clock#479]
Thanks for implementing material themed analog clock widget. But it is only 12 hours.

Can there be a 24 hour format analog widget with 12 hr (noon) at the top & 24 hr (midnight) at bottom - to mimick sun?

This 24hr analog format was also suggested by @git001 at https://github.com/SimpleMobileTools/Simple-Clock/issues/3#issuecomment-459818700

Thanks.

**Comment by tibbi** [comment]
that is taken from your system, we cannot customize it
