### ISSUE TITLE
[Feature Request] Button to select one time occurrence of alarm at the alarm days selector

### ISSUE THREAD

**Issue by inson1** [SimpleMobileTools/Simple-Clock#481]

**Comment by tibbi** [comment]
it already triggers at next occurrence if all days are deselected

**Comment by inson1** [comment]
That is only next day, what if I want one time in Tuesday and tomorrow is Monday etc?

**Comment by tibbi** [comment]
we dont support that

**Comment by inson1** [comment]
yea this is why I created Feature Request
