### ISSUE TITLE
[Bug] App show wrong Alarm in Widget/Frontpage

### ISSUE THREAD

**Issue by TobiScience** [SimpleMobileTools/Simple-Clock#485]
Hello,
your app is really great and usefull
but something with the next alarm doesn't show correctly

when you create an alarm just for a couple days and special without monday, the app widget and frontpage shows something different.

example:
I create a alarm for friday 12:35, the widget shows next alarm tuesday 1:41

I use v5.10.3 android on a samsung phone

thanks 
regards

**Comment by tibbi** [comment]
version 5.10.3? It doesnt even exist

**Comment by TobiScience** [comment]
https://github.com/SimpleMobileTools/Simple-Clock/releases/tag/5.10.3

**Comment by tibbi** [comment]
oh sorry, it has a typo in changelog

**Comment by Anonymous1157** [comment]
I have the same problem with the same app version. The home screen widget shows a seemingly random alarm day and time and the app sends random upcoming alarm notifications, even if the system alarm quick tile and this app's main UI agree which alarms are set.

**Comment by simonjones49** [comment]
Same issue, same version
