### ISSUE TITLE
Alarm-volume is lowered system-wide when an alarm wakes the display

### ISSUE THREAD

**Issue by jp-berg** [SimpleMobileTools/Simple-Clock#493]
# Steps to reproduce

1. Raise the alarm-volume to the max.
2. Set an alarm
3. Ensure the display is off, when the alarm is due

# Expected behavior

* Hear the alarm at the expected volume
* Maybe lower the volume if there is some user interaction with the device
* The global alarm volume should be unaffected by this event
* (Works like this in the Google-clock-app)

# Observed behavior

* The alarm starts out loud, but then lowers in volume as soon as the display turns on to show the alarm screen (so less than a second of 'usable' alarm volume)
* The global alarm volume will be lowered significantly after the alarm is triggered, raising the potential to miss future alarms.

# Information

**Hardware:** Fairphone 4
**Android:** 12
**Simple Clock:** 5.10.3

**Comment by tibbi** [comment]
is it affected by the "Increase volume gradually" app setting?
