### ISSUE TITLE
Simple Clock is not showing Daylights Saving time hours correctly for the US. [issue]

### ISSUE THREAD

**Issue by Mirppc** [SimpleMobileTools/Simple-Clock#5]
As i write this the Time in Los Angeles is 6:10PM and when using the simple clock app it shows it as 5:10PM.  This is a bit of an issue

**Comment by ChrisThompsonTLDR** [comment]
Having the same issue.

**Comment by tibbi** [comment]
what app version do you have? It should be fixed in 3.1.1

**Comment by djdalfaro** [comment]
Confirmed this update fixed it for me.

**Comment by Mirppc** [comment]
it is fixed now, i got the update on fdroid.
