### ISSUE TITLE
[Feature suggestion] Warnings for upcoming DST changes

### ISSUE THREAD

**Issue by slashdevslashurandom** [SimpleMobileTools/Simple-Clock#514]
I believe that it would be helpful if there were an option for the "clock" mode to indicate if a Daylight Savings Time change is about to happen in another timezone (for example, 2 weeks or 1 month in advance).

For example, if it's late September and I have clocks for New York, London and Sydney, the app could display something like this:

**London** 18:55  
*DST ends on 29 Oct (-1 hr)*

**New York** 13:55  

**Sydney** 03:55  
*DST starts on 01 Oct (+1 hr)*

When late October arrives, it could then display below New York that 

*DST ends on 07 Nov (-1 hr)*

and so on

**Comment by tibbi** [comment]
that is way too advaned for this app, so dont expect having it
