### ISSUE TITLE
[Feature Request] Add Default Alarm and Alarm Volume Changing Setting

### ISSUE THREAD

**Issue by ionuttbara** [SimpleMobileTools/Simple-Clock#538]
A feature which you can change alarm volume and default alarm for all alarms  in settings.

**Comment by tibbi** [comment]
volumes are handled by the system, not some app

**Comment by inson1** [comment]
And default alarm is duplicate of #133

**Comment by ionuttbara** [comment]
> Member

but some apps such Google Clock and another F-Droid Project it have the ability to change alarm's volume in the app settings.
