### ISSUE TITLE
AWESOME LOGO DESIGN FREE FOR YOU 

### ISSUE THREAD

**Issue by abdulmalikkhan655** [SimpleMobileTools/Simple-Clock#54]
Hello, @SimpleMobileToolsI want to contribute in "Simple-Clock" so i  want to designed a new logo for "Simple-Clock" and it's free.

I hope you like it. If you like it, I will send you pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.
if you want i will send you my design

contact me on facebook for fast delivary 
https://www.facebook.com/abdulmalikkhan655

**Comment by TacoTheDank** [comment]
yeah bot pretty much confirmed

![screenshot_2018-05-15-08-10-21](https://user-images.githubusercontent.com/32376686/40055912-98f97422-5817-11e8-8fcf-c63f6ab17027.png)

**Comment by abdulmalikkhan655** [comment]
hehehe i am not bot dear i send manual sms for contribution for logo

**Comment by TacoTheDank** [comment]
yeah I know kinda, I saw you responding in the Stringlate issue, but even then, you're just copy-pasting in every project T_T

**Comment by abdulmalikkhan655** [comment]
@TacoTheDank  yes bro its right
