### ISSUE TITLE
Alarm cancels if screen rotates

### ISSUE THREAD

**Issue by JasonMaggini** [SimpleMobileTools/Simple-Clock#540]
I have noticed that on 5.11.2 (and 5.11.1) if the screen changes orientation from portrait to landscape as the alarm is going off (usually when I pick the phone up in the morning), then the alarm cancels. 

I have rolled back to 5.10.3 as it does not exhibit the behavior.

Galaxy A11/Android 11

**Comment by tibbi** [comment]
it will be fixed in the next app version released soon
