### ISSUE TITLE
Change Checkbox to Toggle button in Alarms

### ISSUE THREAD

**Issue by inson1** [SimpleMobileTools/Simple-Clock#544]
I think it would look better

**Comment by tibbi** [comment]
toggles look really bad and unintuitive

**Comment by inson1** [comment]
> toggles look really bad and unintuitive

Xiaomi use it and I love it
![Screenshot_2023-10-18-12-51-33-733_com.android.deskclock.jpg](https://github.com/SimpleMobileTools/Simple-Clock/assets/75314629/50be489d-ed67-40af-b2f5-acab81f58655)

**Comment by tibbi** [comment]
now try having 1 toggle only, you wont even know if it is on or off

**Comment by inson1** [comment]
> now try having 1 toggle only, you wont even know if it is on or off

1) the color
2) its on right side

**Comment by inson1** [comment]
sorry for spam, I'm just reorganizing my solved issues - jg8tzJHCu0Qcc1zJGcht
