### ISSUE TITLE
The clock is too small

### ISSUE THREAD

**Issue by Olejja** [SimpleMobileTools/Simple-Clock#547]
Judging by the preview it should look like this

![Screenshot_20231030-111751](https://github.com/SimpleMobileTools/Simple-Clock/assets/131783541/3feef7b7-87aa-4728-98c5-79e0c1231df8)

but the results are like this

![Screenshot_20231030-111341](https://github.com/SimpleMobileTools/Simple-Clock/assets/131783541/f405fd23-f70a-4d99-bbde-9f062daa3323)

Android version 7.1.2

**Comment by tibbi** [comment]
just long press it and drag sides to resize

**Comment by Olejja** [comment]
> just long press it and drag sides to resize

![Screenshot_20231102-061050](https://github.com/SimpleMobileTools/Simple-Clock/assets/131783541/7caa10e1-b133-4078-8c5f-941323068046)

**Comment by Olejja** [comment]
![Screenshot_20231102-061050](https://github.com/SimpleMobileTools/Simple-Clock/assets/131783541/52ce6494-1f31-4e03-a63d-41ce7d1af59b)

**Comment by tibbi** [comment]
what OS version are you using? Isnt it something extra old?

**Comment by Olejja** [comment]
LineageOS 14.1

There are more recent versions, but the encryption on my device does not work for them...

**Comment by Olejja** [comment]
Ok, I understand that you won’t fix anything.
