### ISSUE TITLE
Re - Issue #533 : alarm stops when smartphone is horizontal

### ISSUE THREAD

**Issue by Moonay-TeamCoffee** [SimpleMobileTools/Simple-Clock#551]
Issue #533 

Issue was closed, "solved" but the update has yet to be released to the Fdroid repository, and my message in the issue 533 has not been answered (_since it also it did not re-open the issue_)
It's been over a month, and for an issue rendering the app useless, it's already too much, especially since the problem has apparently been fixed here.
Can we please get an update to the Fdroid repository?

Thank you.

**Comment by tibbi** [comment]
well, the app hasnt been updated yet, it isnt just about fdroid
