### ISSUE TITLE
[Feature Request] Support for date display formats in different languages

### ISSUE THREAD

**Issue by libook** [SimpleMobileTools/Simple-Clock#557]
Example for Chinese users.
Current date display format is `{Week}, {Day} {Month}`. For example:
```
周日, 4 2月
```
*(Which means Sunday, February 4)*

But in Chinese, date is usually written in the order of `{Month}{Day}，{Week}`. For example:
```
2月4日，周日
or
2月4日，星期日
```

I don't know enough about Android development to know if Android provides APIs for i18n time display format.

**Comment by inson1** [comment]
@libook SMT apps were sold to ad company. Fork is here https://github.com/FossifyOrg

**Comment by libook** [comment]
> @libook SMT apps were sold to ad company. Fork is here [@FossifyOrg](https://github.com/FossifyOrg)

Okay, I got it.
