### ISSUE TITLE
Skip the next reminder while switching it off, but keep it alive

### ISSUE THREAD

**Issue by guy-teube** [SimpleMobileTools/Simple-Clock#559]
Hi there,
On Android 6, I had a useful feature: clicking on the desactivation button, the application asked me if I would like to skip the next reminder but keep the reminder activated, or turn off this reminder.
Now I have Android 13 (with LineageOS 20), but this feature is no more provided with the default clock application.
I use the Simple Clock application too, so I wonder if it would be possible to have this feature.
I attach a screenshot of thie feature on Android 6.
To use it:
1. when the reminder is on, click on the blue button switch
2. The question below is asked, with the choice of deactivate only one time (skip the next reminder and keep it alive), or deactivate the reminder for good.
I hope the issue is clear, ask me if not.
Thank you in advance.

![Screenshot_2024-02-20-08-53-26-755_com android deskclock](https://github.com/SimpleMobileTools/Simple-Clock/assets/18379228/10ce437c-0394-4854-8fe7-25d0d5ecb743)

**Comment by guy-teube** [comment]
@inson1 Ok thanks for the info. Should we uninstalled these apps? Some are still updated.

**Comment by inson1** [comment]
@guy-teube It depends where are they from? just download versions from f-droid if fossify didnt release them yet, (only gallery has lost functionality, so it may be worth using pro version from github (or maybe even google play as idk what they will do wit pro versions apps))

https://www.reddit.com/r/SimpleMobileTools/comments/19a8fq8/15_yes_fifteen_dollars_a_week_for_the_simple/

**Comment by inson1** [comment]
@guy-teube so they cant be updated

**Comment by guy-teube** [comment]
I don't understand how to install the new apps from https://github.com/FossifyOrg

**Comment by guy-teube** [comment]
Ok thank you, I'll be patient and check when it's done.
When it will be released, I'll post the same issue on the other project, but I don't want to overload you with work so I wait :)

**Comment by inson1** [comment]
Its not my work and you can now, but https://github.com/FossifyOrg/Clock/issues/13 should be it, right?

**Comment by guy-teube** [comment]
You are right, thanks!
