### ISSUE TITLE
Option for one-time alarms

### ISSUE THREAD

**Issue by esmoak** [SimpleMobileTools/Simple-Clock#58]
Currently, alarms stay flipped to on position after acknowledging them with the dismiss button.

It would be nice to have the option to set dismiss to turn the alarm off completely (toggle switch by alarm to off position) as a separate setting.

Scenario: I use lots of random alarms to remind me of deadlines at work. And they are never for the same time each day. If the alarm could be flipped off with the dismiss button then I wouldn't have to manually turn each alarm off when done.

For reference, that's basically what Google clock defaults to do, which you are probably already aware of.

**Comment by Gettyk** [comment]
This option would be really great! Please add it, thanks!

**Comment by NicoHood** [comment]
I also think that this is one of the most important features of a clock.

**Comment by ltGuillaume** [comment]
Would be a pivotal change.

**Comment by tibbi** [comment]
will be fixed in 5.4.0

**Comment by eandersons** [comment]
>It would be nice to have the option to set dismiss to turn the alarm off completely (toggle switch by alarm to off position) as a separate setting.

>will be fixed in 5.4.0

If I understand correctly what the author of this issue meant, version 5.4.0 does not turn off an alarm that is not set to repeat on specified days once it is dismissed nor there is a setting to opt in for such behavior.
