### ISSUE TITLE
Add ability to use music for alarm [feature request]

### ISSUE THREAD

**Issue by Mirppc** [SimpleMobileTools/Simple-Clock#6]
Is it at all possible to allow the ability to use stored music (mp3 files or FLAC etc) for the alarm clock?  the default ring tones are useless and dont wake me up compared to playing something like some heavy metal.

**Comment by Primokorn** [comment]
I have a very similar feature request:
Being able to play random files from a specific folder. I have several alarm sounds and I don't want to play the same sound every day.

Thanks for this new app btw.

**Comment by tibbi** [comment]
ye it is on the roadmap, will be added someday

**Comment by KrasnayaPloshchad** [comment]
[Clock L](https://play.google.com/store/apps/details?id=com.moblynx.clockl) is already implemented.

**Comment by Mirppc** [comment]
@KrasnayaPloshchad i prefer to have my apps from Fdroid and i already got an app that works fine from Fdroid for the alarm that allows me to use FLAC files as alarm noises.  If it had the feature simple clock has with the ability to load multiple time zone making it easier to communicate with people in europe, asia and various locations in america, then i would not be here.

**Comment by private-lock** [comment]
So far Simple-Clock stands out from the tons of mediocre alarm clocks by *NOT* requesting any access rights, including files. So in a sense, this feature might well invalidate the "simple" mission of the app. On the other hand, those ringtones get boring really quick!

People understand many different things by requesting music playback. So lets go through the possibilities, as I see them now:

1. Simply select a single fixed song!
   1. gets as boring as the ringtones
   1. should it stop after one go or loop endlessly?
   1. some mp3 start very harsh making me sit upright in bed ... usually ringtones don't - therefore adding music involves gradually increasing volume
1. Play a bunch of songs
   1. simply use all music found on the device
      1. I don't want to wake up to a random chapter of my latest audio-book or some audio-notes recorded at work
   1. add multi-file-selection
      1. tedious to keep up to date (music may be added/deleted at times)
   1. support m3u-playlist-files
      1. they get outdated quickly
      1. a nice hack to support power-users who know how to generate playlists semi-automatically
   1. try clever things selecting interpret or genre from tags
      1. many tags are in an awful state - data is not reliable
   1. play a single folder
      1. the most obvious to me - but somehow missing in many music-alarm-clocks, as the concept of a folder hierarchy is hidden from phone users by all means ... therefore a lot of people don't care, where their music is scattered all over the place
      1. should recursively include sub-folders?
  1. select multiple folders to play
      1. folders don't change as fast a filenames
      1. default should cover the music and the download folder
  1. start a dedicated music-player app (e.g. simple music player)
      1. will browse your music collection for free
      1. could show nice cover pictures
      1. supports tags, if they are available
      1. plays online sources / radio streams
      1. won't stop playback by itself again (ever forgot your phone hooked to a wall outlet at work?)
      1. won't output music to alarm channel, bypassing mute state

So far, I haven't found an alarm-app covering all use-cases. And once you did, we might want to talk about the mission of "simple" again.

Oh and while I'm at it: There is a feature-request-followup:
Once my phone plays music, I hate it, when a song is cut off in the middle. So, please find a way to just properly stop playback at the end of a song. Ideally an alarm would be tagged with two numbers of minutes (min / max duration), for how long the music should play and Simple-Clock fills up a random playlist (no duplicates), until it stops within the constraints. Of course, if the constraints cannot be met (e.g. insufficient music provided / deleted), it should warn about this and fallback to playing a ringtone.

**Comment by oluc** [comment]
it seems the original request "ability to use stored music" is implemented, as you can "Add a new sound" to an alarm. Right?

About playing random sounds, should it be a new ticket, or discussed here?

Could it be just "Add a new sound folder/playlist", (the same way there's "Add a new sound"),
and then a checkbox "shuffle play" ?

something like,

SOUNDS SELECTION
```
+-----------------------
Your sound
(_) my song 1
(_) my song 2
(o) my playlist 1
(_) Add a new sound        ==> open file browser
(_) Add a new playlist     ==> open folder browser

System sounds
...
...
+-----------------
```

ALARM PANEL
```
+------------------
08:00
(M)(T)(W)(T)(F)(S)(S)
Vibrate                   (##)
my playlist 1
Shuffle play              (##)
my alarm name
                 CANCEL    OK
+---------------------------
```

**Comment by tibbi** [comment]
custom audio has been added already
