### ISSUE TITLE
Widget - shows alarm time while no alarm is turned on

### ISSUE THREAD

**Issue by sanmue** [SimpleMobileTools/Simple-Clock#60]
Seems it simply shows the first alarm in the list although no alarm is turned on.
I would prefer not to show an alarm time in this case or an info like "No alarm set"... or something like that below the timepiece.

**Comment by GuitarBilly** [comment]
Nokia6 on android 7.1.2 and SC 4.0.1
FYI - I can not confirm this bug on my phone. After disabling all alarms the current day of the week is shown below the time. After enabling one or more alarms the next upcoming alarm is shown below the time and current day of the week.

**Comment by tibbi** [comment]
do other clock apps work fine? If they do and the issue can still be reproduced, reopen the issue.
