### ISSUE TITLE
Feedack

### ISSUE THREAD

**Issue by bb1a2** [SimpleMobileTools/Simple-Clock#61]
Hi, :)

Version: 4.0.1 on Android 8.0

Quick feedback:

**World clock**:
- Show difference from home clock (e.g. +2:00 in green for clocks ahead, -1:30 in red for clocks behind). Or less stark colors :)

- If possible, tell whether DST is on for that location.

**Alarms**:
- Creating a new alarm should automatically focus on editing time. For examples, see [Alarm Klock](https://play.google.com/store/apps/details?id=com.angrydoughnuts.android.alarmclock) or [Clock+](https://play.google.com/store/apps/details?id=com.philliphsu.clock2).

- ~~Slide to dismiss. This prevents sleepy tapping of stop instead of snooze. (see Alarm Klock)~~

- If no day is selected, make it a one time alarm.

- Auto snooze: After x minutes of alarm (e.g. 5 minutes), snooze for y minutes (e.g. 5 minutes), then start again for x minutes, until z time has passed (e.g. 1 hour).

Thank you :)

---
Edit: sorry for the typo in the title :)

**Comment by bb1a2** [comment]
Thanks for adding the slide feature :)

Can you please making full width i.e. slide from left to right/right to left not from the middle.
|Dismiss>>>>>>>>>|
|<<<<<<<<<Snooze|

Also, action (dismiss/snooze) should not be performed until finger is lifted from screen.

Thanks again :)

**Comment by tibbi** [comment]
the current behaviour is intended. On my device the calling goes from the middle, thats what makes sense to me too. Also I want to react on reaching some side as soon as possible to avoid some glitches.

**Comment by bb1a2** [comment]
OK. Thanks for your response.

**Comment by bb1a2** [comment]
By the way, when the alarm is dismissed, it still creates an entry in Recent Apps instead of main UI. When that entry is tapped, the alarm starts again.

**Comment by tibbi** [comment]
there have been many improvements since this report, create 1 new issue per thing please. Do not mix multiple together
