### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by mlopezgva** [SimpleMobileTools/Simple-Clock#63]
I detected some errors in Spanish texts, I would like to correct and pull. But my knowledge of mobile is limited. I've tried to find the translations in the repository, but coudn't find any.

**Comment by tibbi** [comment]
The guide to translating is at https://github.com/SimpleMobileTools/General-Discussion#how-can-i-suggest-an-edit-to-a-file . The Clock app itself hasnt been translated at all yet, Ive just created a file containing the strings to be translated at https://github.com/SimpleMobileTools/Simple-Clock/blob/master/app/src/main/res/values-es/strings.xml . There is another repo which contains strings reused by multiple apps at https://github.com/SimpleMobileTools/Simple-Commons/blob/master/commons/src/main/res/values-es/strings.xml , you can check it out too. Thanks
