### ISSUE TITLE
activating/inactivating an alarm doesn't work if button is swiped

### ISSUE THREAD

**Issue by Obsidien** [SimpleMobileTools/Simple-Clock#65]
The switch used for activating or inactivating an existing alarm works great if it is clicked, like if it was an old style toggle button, but it doesn't work (while visually updating) if you make the gesture of swiping right (activating) or left (inactivating). Android 4.3 and similar.

**Comment by GuitarBilly** [comment]
nokia6 on android 7.1.2   SC 4.0.1
i can confirm this behavoir. 
FYI - when tapping the toggle ON it always pops a notification "alarm will sound in ....hr/min". When swiping the toggle ON it does not show any notification. Should be logically related to the fact that the alarm is not activated by the swipe.
