### ISSUE TITLE
Simple Clock v 4.0.1. Problems suppressing "Use English Language" feature on Android 7.1.2 N2G47H

### ISSUE THREAD

**Issue by ramulah1** [SimpleMobileTools/Simple-Clock#66]
#### Expected behavior
should, when I press the "Use English Language" feature in the simple clock app the display of the language will change, but the language display remains unchanged.

#### Actual behavior
when I use the app and change the "Use English Language" setting in the simple clock app, its input language does not change even though I have changed the settings icon repeatedly.

#### How to reproduce
1. Install app.
2. Open the app.
3. Click on the icon (other options) in the simple clock app.
![IMG_20180602_152459.jpg](https://cdn.steemitimages.com/DQmbz78DPmjQsm75Pa5dy51GMohUbQY1AChYGjJ7VBGhYso/IMG_20180602_152459.jpg)

4. Click on the settings feature then select the "Use English" feature, after you click it repeatedly, then you will find the same problem as I experienced.

![IMG_20180602_152343.jpg](https://cdn.steemitimages.com/DQmSp3Xde9xR8bjjo8kJcmxCTjSMV9pgdURxdBUT6mVHKbg/IMG_20180602_152343.jpg)

![Screenshot_2018-06-02-15-26-12-803_com.simplemobiletools.clock.png](https://cdn.steemitimages.com/DQmNzDYmFKE8FHHvmuwACLWLg7YEfeGekj8r8cBcyD21eLs/Screenshot_2018-06-02-15-26-12-803_com.simplemobiletools.clock.png)

----
- Device: Redmi Note 5A
- Operating system: 7.1.2 N2GHz
- (CPU: Octa-core Max 1.40 GHz, RAM: 3 GB)

Application Version: 
4.0.1

#### Recording Of The Bug
https://youtu.be/uMR4RxIMo5M

**Comment by tibbi** [comment]
will be fixed in the next version

**Comment by ramulah1** [comment]
ok no problem mr tibbi , maybe it's just a trivial matter
