### ISSUE TITLE
Timer input without spinners

### ISSUE THREAD

**Issue by rerobins** [SimpleMobileTools/Simple-Clock#68]
Please allow timer times to be inputted through keyboard entry instead of spinners.

**Comment by MartinGSch** [comment]
I would also welcome this feature request. If you have any doubts about it, enter a time of 30 min... a pain with the spinners. In fact the spinners in the clock app that Sony delivers have been the trigger for me to start looking for an alternative app.

**Comment by bokf** [comment]
I like the way to input the time from cyanogenmod pressing the digits. It is very fast and easy.


![screenshot_2018-10-08-11-30-58](https://user-images.githubusercontent.com/25562831/46605562-37b45500-cafa-11e8-9168-cfba7e64c184.png)

**Comment by ltGuillaume** [comment]
Same here. Spinners are a real pain.

**Comment by alexanderdd** [comment]
Anybody know a command/module/library that can be  implemented to allow keyboard input?

**Comment by tibbi** [comment]
duplicate of #404
