### ISSUE TITLE
Countdown timer goes into negative numbers!

### ISSUE THREAD

**Issue by serj-kzv** [SimpleMobileTools/Simple-Clock#69]
**Device:** Nokia X2  
**OS:** Android 4.3 (linux 3.4.0)  
Steps to reproduce:
1. Run app
2. Set timer and run.
**UPD** There are no such problems with other timers.

![screenshot_2018-06-17-11-47-30](https://user-images.githubusercontent.com/22834344/41506333-79e7f17c-7224-11e8-9905-cd1d50ac2977.png)

**Comment by tibbi** [comment]
that is intentional to see how long ago it expired

**Comment by serj-kzv** [comment]
Yeah, sorry for that. (: I see now. I was confused because another bug with no sound that I posted in issues.
