### ISSUE TITLE
(Timer) No vibration when screen is turned off.

### ISSUE THREAD

**Issue by serj-kzv** [SimpleMobileTools/Simple-Clock#70]
**Device:** Nokia X2  
**OS:** Android 4.3 (linux 3.4.0)  

**Steps to reproduce:**
1. Run app
2. Set timer, disable sound, enable vibration, run and switch off device screen.

**Result:** no sound, no vibration.  

**P.S.** There are no such problems with other timers.

**UPD.** Sometimes It works, sometimes no.

**Comment by tibbi** [comment]
such things are done by the system.
