### ISSUE TITLE
Please set application status to Beta

### ISSUE THREAD

**Issue by serj-kzv** [SimpleMobileTools/Simple-Clock#71]
There are too many bugs for such important application as "alarm and timer". Please, set the application to the **Beta** status and add the **Beta** status to the application name as a `Simple-Clock Beta` until most of these bugs will be fixed.

**Comment by tibbi** [comment]
there is a dialog warning to test the alarm before making sure it works. It works fine to most people, there are just many system limitation depending on the manufacturer and OS that break it in some cases.

**Comment by serj-kzv** [comment]
It's pity. I think you understand that people use alarm to go and they won't use any alarm that doesn't work sometimes. Also it's very dangerous for people who take a drugs by timer.

**Comment by tibbi** [comment]
well that is the way devices work. Sadly sometimes the OS decides not to trigger it. Theres not much I can do about it. If you check Google Clock reviews, you can see many people with alarm issues too https://play.google.com/store/apps/details?id=com.google.android.deskclock&showAllReviews=true . If Google cant make it reliably, I cant either.

**Comment by serj-kzv** [comment]
Thanks for the link, It's very informative situation. Now I will use a my OS stock alarm only. Unfortunately the my stock OS has no a built in timer and I need to use a third party timer. Interesting that there is no convenience open source timer that works well on the my OS. There are few timers on F-Droid and they work well but their UI is really bad.

**Comment by tibbi** [comment]
sadly some device manufacturers want to be too smart around battery saving so they either cause some background tasks to be unreliable, or they simple shut them off. You might have some extra settings around your battery settings too, maybe some settings per app.

**Comment by serj-kzv** [comment]
I remember. (: There is some special stuff for Nokia X applications http://developers.apps.opera.com/nokia-x
