### ISSUE TITLE
[4.1.0] Timer countdown stops when screen is off

### ISSUE THREAD

**Issue by sledgehammer999** [SimpleMobileTools/Simple-Clock#77]
OS: Lineage OS 14.1

This started happening with 4.1.0. It worked flawlessly with 4.0.1 (both versions from fdroid).

I have a timer of 38 seconds. Vibrate is on. No sound.
I start it and I turn the screen off. With 4.0.1 the timer continued running and when it expired it started vibrating and the screen lit up allowing me to stop it.
Now with 4.1.0, the timer seems to stop the countdown with about 20 seconds remaining when the screen is off. When I turn the screen on and unlock it, the timer countdown continues.
If I leave the screen on from the start the problem doesn't exist.

I verified this by going back to 4.0.1 and it continues to work.
With 4.1.0 I even disabled battery optimization but it still didn't work.

**Comment by Gettyk** [comment]
Hi, 

I am having a similar problem with cyanogenmods 13. 
 I also disable battery optimization.

**Comment by Joppla** [comment]
When will it be solved?

**Comment by tibbi** [comment]
should be soon
