### ISSUE TITLE
Expired timer continues countdown into negative numbers when screen is on

### ISSUE THREAD

**Issue by sledgehammer999** [SimpleMobileTools/Simple-Clock#78]
If I leave the screen on and watching the timer,  the countdown goes into negative numbers after it reaches zero. While simultaneously playing the sound/vibrating.

If I pause it in the negative numbers and unpause it, it continues the countdown into the negative numbers.

It should stop at zero and start vibrating/playing the sound. Once the play/pause button is pressed notification should stop and the timer should be reset. Like it does when it expires while the screen is off.

**Comment by tibbi** [comment]
that is intentional, to know how long ago it expired
