### ISSUE TITLE
Possible bug with Android major version update?

### ISSUE THREAD

**Issue by krc** [SimpleMobileTools/Simple-Clock#80]
I just updated my Samsung Galaxy S7 (flat) from 7 to 8, with Samsung SmartSwitch (including backup and restore). And while the alarm listings were all there, and on, it seem they didn't go off. I toggled them off and then on, the last one just now went off fine. (Simple Clock was fully updated)

Of course it's also possible the earlier alarms went off, but I ended them without waking up fully, and then couldn't remember it. It has happened before, though not recently (one reason I have multiple alarms). But if you could take a look and see if it seems like a thing that could happen that would be great. I wouldn't want anyone else to get hit by such bug in a bad way. Thanks for all your work with these apps!

**Comment by tibbi** [comment]
If you try scheduling an alarm 2 minutes in the future and keep the app foregrounded, does it trigger?
