### ISSUE TITLE
Make the list of timezones more compact, in order to improve visibility

### ISSUE THREAD

**Issue by WPFilmmaker** [SimpleMobileTools/Simple-Clock#81]
The "add timezone" button makes impossible to see the time when many time zones are added as you can see from the screenshot: http://oi66.tinypic.com/flkb4x.jpg the big "+" button blocks the view.

I propose to make the list of time zones more compact:

1 If the timezone shows a different day move it next to the time rather than under it

2 Move each different timezone closer to each other in order to save space

3 Move the "+" button somewhere under the big current time (there are two big empty spaces) and/or make it smaller or change its shape.

 Screenshot: http://oi67.tinypic.com/2cntnib.jpg

Thank you.

**Comment by tibbi** [comment]
bottom padding will be added in 5.4.0, I dont really want to increase item margins. It would be too crowded
