### ISSUE TITLE
all clocks reset upon exiting the app

### ISSUE THREAD

**Issue by RoughCurve** [SimpleMobileTools/Simple-Clock#87]
How to reproduce the bug:
1.set your alarm
2.press home button
3.all your alarms are now off.

Galaxy s7, sm-930fd, android 7.1.2
LineageOS 14.1 herolte

**Comment by tibbi** [comment]
cannot reproduce. What app version do you have? Does it still happen?

**Comment by RoughCurve** [comment]
Sorry for the delay, just managed to reproduce it in version 4.2.0, uninstalled previous version a while ago so can't test the earlier one. What i did to reproduce it was:

Downloaded app from f droid
Populated app with 8 random alarms
Activated all of them
Press home button
Deactivated 1 alarm
Press home button

Result: all of the alarms are still activated, only reproduced with home button, with the 'back' button it doesn't happen.
I can record my screen to show you, if you'd like.

-------- Original Message --------

**Comment by tibbi** [comment]
Activated all of them
Press home button
Deactivated 1 alarm

How have you deactivated the alarm while the app was in the background?

**Comment by RoughCurve** [comment]
Forgot to add the step "entered the app again" in between
