### ISSUE TITLE
"+" button on alarms obscures toggle for fourth alarm

### ISSUE THREAD

**Issue by JasonWoof** [SimpleMobileTools/Simple-Clock#96]
You've got overlapping UI elements that basically make it impossible to hit the enable/disable button on the 4th alarm (on my screen size).

**Comment by Nomuit** [comment]
This has been brought up in other issues as well (#25, #30/34, #81), but despite ChiefMikeK's recommendation in 30/34 to make the **+** smaller, I'd recommend just adding a small empty entry at the bottom of the list, similar to what Samsung Experience's default Clock app features (see pic below).

That should enable the **+** to work on just about any phone resolution/size, or at least close enough it shouldn't become a hassle anymore, while having minimal additional work.

https://i.imgur.com/FF3MTAA.jpg?1
